import astropy.table as apTab
import astropy.units as u
import lsst.daf.butler as dafButler
from lsst.daf.butler.formatters.parquet import astropy_to_arrow, compute_row_group_size
from lsst.geom import degrees, SpherePoint
import numpy as np
import pyarrow.parquet as pq

skymap = "lsst_cells_v1"
tract = 5063
name_tab = "hlsp_jades_jwst_nircam_goods-s-deep_photometry_v2.0_catalog"
filename = f"{name_tab}.fits"
butler = dafButler.Butler("/repo/main", collections="skymaps")
tractInfo = butler.get("skyMap", skymap=skymap)[tract]

columns_hdu = {
2: {
    "ID": ("", "Unique ID of source"),
    "RA": ("deg", "RA of source, ICRS, from detection image"),
    "DEC": ("deg", "Dec of source, ICRS, from detection image"),
    "F090W_FLAG": ("", "Number of bad pixels in band"),
    "F115W_FLAG": ("", "Number of bad pixels in band"),
    "F150W_FLAG": ("", "Number of bad pixels in band"),
    "F182M_FLAG": ("", "Number of bad pixels in band"),
    "F200W_FLAG": ("", "Number of bad pixels in band"),
    "F210M_FLAG": ("", "Number of bad pixels in band"),
    "F277W_FLAG": ("", "Number of bad pixels in band"),
    "F335M_FLAG": ("", "Number of bad pixels in band"),
    "F356W_FLAG": ("", "Number of bad pixels in band"),
    "F410M_FLAG": ("", "Number of bad pixels in band"),
    "F430M_FLAG": ("", "Number of bad pixels in band"),
    "F444W_FLAG": ("", "Number of bad pixels in band"),
    "F460M_FLAG": ("", "Number of bad pixels in band"),
    "F480M_FLAG": ("", "Number of bad pixels in band"),
    "F435W_FLAG": ("", "Number of bad pixels in band"),
    "F606W_FLAG": ("", "Number of bad pixels in band"),
    "F775W_FLAG": ("", "Number of bad pixels in band"),
    "F814W_FLAG": ("", "Number of bad pixels in band"),
    "F850LP_FLAG": ("", "Number of bad pixels in band"),
    "F105W_FLAG": ("", "Number of bad pixels in band"),
    "F125W_FLAG": ("", "Number of bad pixels in band"),
    "F140W_FLAG": ("", "Number of bad pixels in band"),
    "F160W_FLAG": ("", "Number of bad pixels in band"),
    "F090W_TEXP": ("s", "Average exposure time in band"),
    "F115W_TEXP": ("s", "Average exposure time in band"),
    "F150W_TEXP": ("s", "Average exposure time in band"),
    "F182M_TEXP": ("s", "Average exposure time in band"),
    "F200W_TEXP": ("s", "Average exposure time in band"),
    "F210M_TEXP": ("s", "Average exposure time in band"),
    "F277W_TEXP": ("s", "Average exposure time in band"),
    "F335M_TEXP": ("s", "Average exposure time in band"),
    "F356W_TEXP": ("s", "Average exposure time in band"),
    "F410M_TEXP": ("s", "Average exposure time in band"),
    "F430M_TEXP": ("s", "Average exposure time in band"),
    "F444W_TEXP": ("s", "Average exposure time in band"),
    "F460M_TEXP": ("s", "Average exposure time in band"),
    "F480M_TEXP": ("s", "Average exposure time in band"),
    "F435W_TEXP": ("s", "Average exposure time in band"),
    "F606W_TEXP": ("s", "Average exposure time in band"),
    "F775W_TEXP": ("s", "Average exposure time in band"),
    "F814W_TEXP": ("s", "Average exposure time in band"),
    "F850LP_TEXP": ("s", "Average exposure time in band"),
    "F105W_TEXP": ("s", "Average exposure time in band"),
    "F125W_TEXP": ("s", "Average exposure time in band"),
    "F140W_TEXP": ("s", "Average exposure time in band"),
    "F160W_TEXP": ("s", "Average exposure time in band"),
    "F090W_WHT": ("", "Average weight in band"),
    "F115W_WHT": ("", "Average weight in band"),
    "F150W_WHT": ("", "Average weight in band"),
    "F182M_WHT": ("", "Average weight in band"),
    "F200W_WHT": ("", "Average weight in band"),
    "F210M_WHT": ("", "Average weight in band"),
    "F277W_WHT": ("", "Average weight in band"),
    "F335M_WHT": ("", "Average weight in band"),
    "F356W_WHT": ("", "Average weight in band"),
    "F410M_WHT": ("", "Average weight in band"),
    "F430M_WHT": ("", "Average weight in band"),
    "F444W_WHT": ("", "Average weight in band"),
    "F460M_WHT": ("", "Average weight in band"),
    "F480M_WHT": ("", "Average weight in band"),
    "F435W_WHT": ("", "Average weight in band"),
    "F606W_WHT": ("", "Average weight in band"),
    "F775W_WHT": ("", "Average weight in band"),
    "F814W_WHT": ("", "Average weight in band"),
    "F850LP_WHT": ("", "Average weight in band"),
    "F105W_WHT": ("", "Average weight in band"),
    "F125W_WHT": ("", "Average weight in band"),
    "F140W_WHT": ("", "Average weight in band"),
    "F160W_WHT": ("", "Average weight in band"),
    "FLAG_ST": ("", "Classification star = 1, galaxy = 0"),
    "FLAG_BS": ("", "Impacted by neighboring bright star"),
    "FLAG_BN": ("", "0 default, 1 if neighbor >2x brighter, 2 if neighbor >10x brighter"),
},
3: {
    "NPIX_DET": ("", "Number of pixels in the detection image belonging to the object"),
    "X": ("pix", "x-centroid in detection image, windowed"),
    "Y": ("pix", "y-centroid in detection image, windowed"),
    "XC": ("pix", "x-centroid in detection image, barycenter"),
    "YC": ("pix", "y-centroid in detection image, barycenter"),
    "BBOX_XMIN": ("pix", "Bounding box x-minimum in detection image"),
    "BBOX_XMAX": ("pix", "Bounding box x-maximum in detection image"),
    "BBOX_YMIN": ("pix", "Bounding box y-minimum in detection image"),
    "BBOX_YMAX": ("pix", "Bounding box y-maximum in detection image"),
    "R_KRON": ("arcsec", "Kron radius with Kron parameter 2.5, from detection image"),
    "A": ("arcsec", "Semi-major axis length, from detection image"),
    "B": ("arcsec", "Semi-minor axis length, from detection image"),
    "FWHM": ("arcsec", "Circular-equivalent full width half max"),
    "F090W_RHALF": ("arcsec", "Half-light radius (circularized) in band"),
    "F115W_RHALF": ("arcsec", "Half-light radius (circularized) in band"),
    "F150W_RHALF": ("arcsec", "Half-light radius (circularized) in band"),
    "F182M_RHALF": ("arcsec", "Half-light radius (circularized) in band"),
    "F200W_RHALF": ("arcsec", "Half-light radius (circularized) in band"),
    "F210M_RHALF": ("arcsec", "Half-light radius (circularized) in band"),
    "F277W_RHALF": ("arcsec", "Half-light radius (circularized) in band"),
    "F335M_RHALF": ("arcsec", "Half-light radius (circularized) in band"),
    "F356W_RHALF": ("arcsec", "Half-light radius (circularized) in band"),
    "F410M_RHALF": ("arcsec", "Half-light radius (circularized) in band"),
    "F430M_RHALF": ("arcsec", "Half-light radius (circularized) in band"),
    "F444W_RHALF": ("arcsec", "Half-light radius (circularized) in band"),
    "F460M_RHALF": ("arcsec", "Half-light radius (circularized) in band"),
    "F480M_RHALF": ("arcsec", "Half-light radius (circularized) in band"),
    "F435W_RHALF": ("arcsec", "Half-light radius (circularized) in band"),
    "F606W_RHALF": ("arcsec", "Half-light radius (circularized) in band"),
    "F775W_RHALF": ("arcsec", "Half-light radius (circularized) in band"),
    "F814W_RHALF": ("arcsec", "Half-light radius (circularized) in band"),
    "F850LP_RHALF": ("arcsec", "Half-light radius (circularized) in band"),
    "F105W_RHALF": ("arcsec", "Half-light radius (circularized) in band"),
    "F125W_RHALF": ("arcsec", "Half-light radius (circularized) in band"),
    "F140W_RHALF": ("arcsec", "Half-light radius (circularized) in band"),
    "F160W_RHALF": ("arcsec", "Half-light radius (circularized) in band"),
},
7: {
    "F090W_KRON": ("nJy", "Flux of source in band within aperture R_KRON"),
    "F090W_KRON_S": ("nJy", "Flux of source in band within aperture R_KRON_S"),
    "F090W_SEG": ("nJy", "Flux of source in band within aperture SEG"),
    "F115W_KRON": ("nJy", "Flux of source in band within aperture R_KRON"),
    "F115W_KRON_S": ("nJy", "Flux of source in band within aperture R_KRON_S"),
    "F115W_SEG": ("nJy", "Flux of source in band within aperture SEG"),
    "F150W_KRON": ("nJy", "Flux of source in band within aperture R_KRON"),
    "F150W_KRON_S": ("nJy", "Flux of source in band within aperture R_KRON_S"),
    "F150W_SEG": ("nJy", "Flux of source in band within aperture SEG"),
    "F182M_KRON": ("nJy", "Flux of source in band within aperture R_KRON"),
    "F182M_KRON_S": ("nJy", "Flux of source in band within aperture R_KRON_S"),
    "F182M_SEG": ("nJy", "Flux of source in band within aperture SEG"),
    "F200W_KRON": ("nJy", "Flux of source in band within aperture R_KRON"),
    "F200W_KRON_S": ("nJy", "Flux of source in band within aperture R_KRON_S"),
    "F200W_SEG": ("nJy", "Flux of source in band within aperture SEG"),
    "F210M_KRON": ("nJy", "Flux of source in band within aperture R_KRON"),
    "F210M_KRON_S": ("nJy", "Flux of source in band within aperture R_KRON_S"),
    "F210M_SEG": ("nJy", "Flux of source in band within aperture SEG"),
    "F277W_KRON": ("nJy", "Flux of source in band within aperture R_KRON"),
    "F277W_KRON_S": ("nJy", "Flux of source in band within aperture R_KRON_S"),
    "F277W_SEG": ("nJy", "Flux of source in band within aperture SEG"),
    "F335M_KRON": ("nJy", "Flux of source in band within aperture R_KRON"),
    "F335M_KRON_S": ("nJy", "Flux of source in band within aperture R_KRON_S"),
    "F335M_SEG": ("nJy", "Flux of source in band within aperture SEG"),
    "F356W_KRON": ("nJy", "Flux of source in band within aperture R_KRON"),
    "F356W_KRON_S": ("nJy", "Flux of source in band within aperture R_KRON_S"),
    "F356W_SEG": ("nJy", "Flux of source in band within aperture SEG"),
    "F410M_KRON": ("nJy", "Flux of source in band within aperture R_KRON"),
    "F410M_KRON_S": ("nJy", "Flux of source in band within aperture R_KRON_S"),
    "F410M_SEG": ("nJy", "Flux of source in band within aperture SEG"),
    "F430M_KRON": ("nJy", "Flux of source in band within aperture R_KRON"),
    "F430M_KRON_S": ("nJy", "Flux of source in band within aperture R_KRON_S"),
    "F430M_SEG": ("nJy", "Flux of source in band within aperture SEG"),
    "F444W_KRON": ("nJy", "Flux of source in band within aperture R_KRON"),
    "F444W_KRON_S": ("nJy", "Flux of source in band within aperture R_KRON_S"),
    "F444W_SEG": ("nJy", "Flux of source in band within aperture SEG"),
    "F460M_KRON": ("nJy", "Flux of source in band within aperture R_KRON"),
    "F460M_KRON_S": ("nJy", "Flux of source in band within aperture R_KRON_S"),
    "F460M_SEG": ("nJy", "Flux of source in band within aperture SEG"),
    "F480M_KRON": ("nJy", "Flux of source in band within aperture R_KRON"),
    "F480M_KRON_S": ("nJy", "Flux of source in band within aperture R_KRON_S"),
    "F480M_SEG": ("nJy", "Flux of source in band within aperture SEG"),
    "F435W_KRON": ("nJy", "Flux of source in band within aperture R_KRON"),
    "F435W_KRON_S": ("nJy", "Flux of source in band within aperture R_KRON_S"),
    "F435W_SEG": ("nJy", "Flux of source in band within aperture SEG"),
    "F606W_KRON": ("nJy", "Flux of source in band within aperture R_KRON"),
    "F606W_KRON_S": ("nJy", "Flux of source in band within aperture R_KRON_S"),
    "F606W_SEG": ("nJy", "Flux of source in band within aperture SEG"),
    "F775W_KRON": ("nJy", "Flux of source in band within aperture R_KRON"),
    "F775W_KRON_S": ("nJy", "Flux of source in band within aperture R_KRON_S"),
    "F775W_SEG": ("nJy", "Flux of source in band within aperture SEG"),
    "F814W_KRON": ("nJy", "Flux of source in band within aperture R_KRON"),
    "F814W_KRON_S": ("nJy", "Flux of source in band within aperture R_KRON_S"),
    "F814W_SEG": ("nJy", "Flux of source in band within aperture SEG"),
    "F850LP_KRON": ("nJy", "Flux of source in band within aperture R_KRON"),
    "F850LP_KRON_S": ("nJy", "Flux of source in band within aperture R_KRON_S"),
    "F850LP_SEG": ("nJy", "Flux of source in band within aperture SEG"),
    "F105W_KRON": ("nJy", "Flux of source in band within aperture R_KRON"),
    "F105W_KRON_S": ("nJy", "Flux of source in band within aperture R_KRON_S"),
    "F105W_SEG": ("nJy", "Flux of source in band within aperture SEG"),
    "F125W_KRON": ("nJy", "Flux of source in band within aperture R_KRON"),
    "F125W_KRON_S": ("nJy", "Flux of source in band within aperture R_KRON_S"),
    "F125W_SEG": ("nJy", "Flux of source in band within aperture SEG"),
    "F140W_KRON": ("nJy", "Flux of source in band within aperture R_KRON"),
    "F140W_KRON_S": ("nJy", "Flux of source in band within aperture R_KRON_S"),
    "F140W_SEG": ("nJy", "Flux of source in band within aperture SEG"),
    "F160W_KRON": ("nJy", "Flux of source in band within aperture R_KRON"),
    "F160W_KRON_S": ("nJy", "Flux of source in band within aperture R_KRON_S"),
    "F160W_SEG": ("nJy", "Flux of source in band within aperture SEG"),
    "F090W_KRON_ei": ("nJy", "Uncertainty of source flux within aperture R_KRON, measured from the ERR extension"),
    "F090W_KRON_S_ei": ("nJy", "Uncertainty of source flux within aperture R_KRON_S, measured from the ERR extension"),
    "F090W_SEG_ei": ("nJy", "Uncertainty of source flux within aperture SEG, measured from the ERR extension"),
    "F115W_KRON_ei": ("nJy", "Uncertainty of source flux within aperture R_KRON, measured from the ERR extension"),
    "F115W_KRON_S_ei": ("nJy", "Uncertainty of source flux within aperture R_KRON_S, measured from the ERR extension"),
    "F115W_SEG_ei": ("nJy", "Uncertainty of source flux within aperture SEG, measured from the ERR extension"),
    "F150W_KRON_ei": ("nJy", "Uncertainty of source flux within aperture R_KRON, measured from the ERR extension"),
    "F150W_KRON_S_ei": ("nJy", "Uncertainty of source flux within aperture R_KRON_S, measured from the ERR extension"),
    "F150W_SEG_ei": ("nJy", "Uncertainty of source flux within aperture SEG, measured from the ERR extension"),
    "F182M_KRON_ei": ("nJy", "Uncertainty of source flux within aperture R_KRON, measured from the ERR extension"),
    "F182M_KRON_S_ei": ("nJy", "Uncertainty of source flux within aperture R_KRON_S, measured from the ERR extension"),
    "F182M_SEG_ei": ("nJy", "Uncertainty of source flux within aperture SEG, measured from the ERR extension"),
    "F200W_KRON_ei": ("nJy", "Uncertainty of source flux within aperture R_KRON, measured from the ERR extension"),
    "F200W_KRON_S_ei": ("nJy", "Uncertainty of source flux within aperture R_KRON_S, measured from the ERR extension"),
    "F200W_SEG_ei": ("nJy", "Uncertainty of source flux within aperture SEG, measured from the ERR extension"),
    "F210M_KRON_ei": ("nJy", "Uncertainty of source flux within aperture R_KRON, measured from the ERR extension"),
    "F210M_KRON_S_ei": ("nJy", "Uncertainty of source flux within aperture R_KRON_S, measured from the ERR extension"),
    "F210M_SEG_ei": ("nJy", "Uncertainty of source flux within aperture SEG, measured from the ERR extension"),
    "F277W_KRON_ei": ("nJy", "Uncertainty of source flux within aperture R_KRON, measured from the ERR extension"),
    "F277W_KRON_S_ei": ("nJy", "Uncertainty of source flux within aperture R_KRON_S, measured from the ERR extension"),
    "F277W_SEG_ei": ("nJy", "Uncertainty of source flux within aperture SEG, measured from the ERR extension"),
    "F335M_KRON_ei": ("nJy", "Uncertainty of source flux within aperture R_KRON, measured from the ERR extension"),
    "F335M_KRON_S_ei": ("nJy", "Uncertainty of source flux within aperture R_KRON_S, measured from the ERR extension"),
    "F335M_SEG_ei": ("nJy", "Uncertainty of source flux within aperture SEG, measured from the ERR extension"),
    "F356W_KRON_ei": ("nJy", "Uncertainty of source flux within aperture R_KRON, measured from the ERR extension"),
    "F356W_KRON_S_ei": ("nJy", "Uncertainty of source flux within aperture R_KRON_S, measured from the ERR extension"),
    "F356W_SEG_ei": ("nJy", "Uncertainty of source flux within aperture SEG, measured from the ERR extension"),
    "F410M_KRON_ei": ("nJy", "Uncertainty of source flux within aperture R_KRON, measured from the ERR extension"),
    "F410M_KRON_S_ei": ("nJy", "Uncertainty of source flux within aperture R_KRON_S, measured from the ERR extension"),
    "F410M_SEG_ei": ("nJy", "Uncertainty of source flux within aperture SEG, measured from the ERR extension"),
    "F430M_KRON_ei": ("nJy", "Uncertainty of source flux within aperture R_KRON, measured from the ERR extension"),
    "F430M_KRON_S_ei": ("nJy", "Uncertainty of source flux within aperture R_KRON_S, measured from the ERR extension"),
    "F430M_SEG_ei": ("nJy", "Uncertainty of source flux within aperture SEG, measured from the ERR extension"),
    "F444W_KRON_ei": ("nJy", "Uncertainty of source flux within aperture R_KRON, measured from the ERR extension"),
    "F444W_KRON_S_ei": ("nJy", "Uncertainty of source flux within aperture R_KRON_S, measured from the ERR extension"),
    "F444W_SEG_ei": ("nJy", "Uncertainty of source flux within aperture SEG, measured from the ERR extension"),
    "F460M_KRON_ei": ("nJy", "Uncertainty of source flux within aperture R_KRON, measured from the ERR extension"),
    "F460M_KRON_S_ei": ("nJy", "Uncertainty of source flux within aperture R_KRON_S, measured from the ERR extension"),
    "F460M_SEG_ei": ("nJy", "Uncertainty of source flux within aperture SEG, measured from the ERR extension"),
    "F480M_KRON_ei": ("nJy", "Uncertainty of source flux within aperture R_KRON, measured from the ERR extension"),
    "F480M_KRON_S_ei": ("nJy", "Uncertainty of source flux within aperture R_KRON_S, measured from the ERR extension"),
    "F480M_SEG_ei": ("nJy", "Uncertainty of source flux within aperture SEG, measured from the ERR extension"),
    "F090W_KRON_e": ("nJy", "NMAD uncertainty of source flux within aperture R_KRON, measured from a series of random apertures"),
    "F090W_KRON_S_e": ("nJy", "NMAD uncertainty of source flux within aperture R_KRON_S, measured from a series of random apertures"),
    "F090W_SEG_e": ("nJy", "NMAD uncertainty of source flux within aperture SEG, measured from a series of random apertures"),
    "F115W_KRON_e": ("nJy", "NMAD uncertainty of source flux within aperture R_KRON, measured from a series of random apertures"),
    "F115W_KRON_S_e": ("nJy", "NMAD uncertainty of source flux within aperture R_KRON_S, measured from a series of random apertures"),
    "F115W_SEG_e": ("nJy", "NMAD uncertainty of source flux within aperture SEG, measured from a series of random apertures"),
    "F150W_KRON_e": ("nJy", "NMAD uncertainty of source flux within aperture R_KRON, measured from a series of random apertures"),
    "F150W_KRON_S_e": ("nJy", "NMAD uncertainty of source flux within aperture R_KRON_S, measured from a series of random apertures"),
    "F150W_SEG_e": ("nJy", "NMAD uncertainty of source flux within aperture SEG, measured from a series of random apertures"),
    "F182M_KRON_e": ("nJy", "NMAD uncertainty of source flux within aperture R_KRON, measured from a series of random apertures"),
    "F182M_KRON_S_e": ("nJy", "NMAD uncertainty of source flux within aperture R_KRON_S, measured from a series of random apertures"),
    "F182M_SEG_e": ("nJy", "NMAD uncertainty of source flux within aperture SEG, measured from a series of random apertures"),
    "F200W_KRON_e": ("nJy", "NMAD uncertainty of source flux within aperture R_KRON, measured from a series of random apertures"),
    "F200W_KRON_S_e": ("nJy", "NMAD uncertainty of source flux within aperture R_KRON_S, measured from a series of random apertures"),
    "F200W_SEG_e": ("nJy", "NMAD uncertainty of source flux within aperture SEG, measured from a series of random apertures"),
    "F210M_KRON_e": ("nJy", "NMAD uncertainty of source flux within aperture R_KRON, measured from a series of random apertures"),
    "F210M_KRON_S_e": ("nJy", "NMAD uncertainty of source flux within aperture R_KRON_S, measured from a series of random apertures"),
    "F210M_SEG_e": ("nJy", "NMAD uncertainty of source flux within aperture SEG, measured from a series of random apertures"),
    "F277W_KRON_e": ("nJy", "NMAD uncertainty of source flux within aperture R_KRON, measured from a series of random apertures"),
    "F277W_KRON_S_e": ("nJy", "NMAD uncertainty of source flux within aperture R_KRON_S, measured from a series of random apertures"),
    "F277W_SEG_e": ("nJy", "NMAD uncertainty of source flux within aperture SEG, measured from a series of random apertures"),
    "F335M_KRON_e": ("nJy", "NMAD uncertainty of source flux within aperture R_KRON, measured from a series of random apertures"),
    "F335M_KRON_S_e": ("nJy", "NMAD uncertainty of source flux within aperture R_KRON_S, measured from a series of random apertures"),
    "F335M_SEG_e": ("nJy", "NMAD uncertainty of source flux within aperture SEG, measured from a series of random apertures"),
    "F356W_KRON_e": ("nJy", "NMAD uncertainty of source flux within aperture R_KRON, measured from a series of random apertures"),
    "F356W_KRON_S_e": ("nJy", "NMAD uncertainty of source flux within aperture R_KRON_S, measured from a series of random apertures"),
    "F356W_SEG_e": ("nJy", "NMAD uncertainty of source flux within aperture SEG, measured from a series of random apertures"),
    "F410M_KRON_e": ("nJy", "NMAD uncertainty of source flux within aperture R_KRON, measured from a series of random apertures"),
    "F410M_KRON_S_e": ("nJy", "NMAD uncertainty of source flux within aperture R_KRON_S, measured from a series of random apertures"),
    "F410M_SEG_e": ("nJy", "NMAD uncertainty of source flux within aperture SEG, measured from a series of random apertures"),
    "F430M_KRON_e": ("nJy", "NMAD uncertainty of source flux within aperture R_KRON, measured from a series of random apertures"),
    "F430M_KRON_S_e": ("nJy", "NMAD uncertainty of source flux within aperture R_KRON_S, measured from a series of random apertures"),
    "F430M_SEG_e": ("nJy", "NMAD uncertainty of source flux within aperture SEG, measured from a series of random apertures"),
    "F444W_KRON_e": ("nJy", "NMAD uncertainty of source flux within aperture R_KRON, measured from a series of random apertures"),
    "F444W_KRON_S_e": ("nJy", "NMAD uncertainty of source flux within aperture R_KRON_S, measured from a series of random apertures"),
    "F444W_SEG_e": ("nJy", "NMAD uncertainty of source flux within aperture SEG, measured from a series of random apertures"),
    "F460M_KRON_e": ("nJy", "NMAD uncertainty of source flux within aperture R_KRON, measured from a series of random apertures"),
    "F460M_KRON_S_e": ("nJy", "NMAD uncertainty of source flux within aperture R_KRON_S, measured from a series of random apertures"),
    "F460M_SEG_e": ("nJy", "NMAD uncertainty of source flux within aperture SEG, measured from a series of random apertures"),
    "F480M_KRON_e": ("nJy", "NMAD uncertainty of source flux within aperture R_KRON, measured from a series of random apertures"),
    "F480M_KRON_S_e": ("nJy", "NMAD uncertainty of source flux within aperture R_KRON_S, measured from a series of random apertures"),
    "F480M_SEG_e": ("nJy", "NMAD uncertainty of source flux within aperture SEG, measured from a series of random apertures"),
    "F435W_KRON_e": ("nJy", "NMAD uncertainty of source flux within aperture R_KRON, measured from a series of random apertures"),
    "F435W_KRON_S_e": ("nJy", "NMAD uncertainty of source flux within aperture R_KRON_S, measured from a series of random apertures"),
    "F435W_SEG_e": ("nJy", "NMAD uncertainty of source flux within aperture SEG, measured from a series of random apertures"),
    "F606W_KRON_e": ("nJy", "NMAD uncertainty of source flux within aperture R_KRON, measured from a series of random apertures"),
    "F606W_KRON_S_e": ("nJy", "NMAD uncertainty of source flux within aperture R_KRON_S, measured from a series of random apertures"),
    "F606W_SEG_e": ("nJy", "NMAD uncertainty of source flux within aperture SEG, measured from a series of random apertures"),
    "F775W_KRON_e": ("nJy", "NMAD uncertainty of source flux within aperture R_KRON, measured from a series of random apertures"),
    "F775W_KRON_S_e": ("nJy", "NMAD uncertainty of source flux within aperture R_KRON_S, measured from a series of random apertures"),
    "F775W_SEG_e": ("nJy", "NMAD uncertainty of source flux within aperture SEG, measured from a series of random apertures"),
    "F814W_KRON_e": ("nJy", "NMAD uncertainty of source flux within aperture R_KRON, measured from a series of random apertures"),
    "F814W_KRON_S_e": ("nJy", "NMAD uncertainty of source flux within aperture R_KRON_S, measured from a series of random apertures"),
    "F814W_SEG_e": ("nJy", "NMAD uncertainty of source flux within aperture SEG, measured from a series of random apertures"),
    "F850LP_KRON_e": ("nJy", "NMAD uncertainty of source flux within aperture R_KRON, measured from a series of random apertures"),
    "F850LP_KRON_S_e": ("nJy", "NMAD uncertainty of source flux within aperture R_KRON_S, measured from a series of random apertures"),
    "F850LP_SEG_e": ("nJy", "NMAD uncertainty of source flux within aperture SEG, measured from a series of random apertures"),
    "F105W_KRON_e": ("nJy", "NMAD uncertainty of source flux within aperture R_KRON, measured from a series of random apertures"),
    "F105W_KRON_S_e": ("nJy", "NMAD uncertainty of source flux within aperture R_KRON_S, measured from a series of random apertures"),
    "F105W_SEG_e": ("nJy", "NMAD uncertainty of source flux within aperture SEG, measured from a series of random apertures"),
    "F125W_KRON_e": ("nJy", "NMAD uncertainty of source flux within aperture R_KRON, measured from a series of random apertures"),
    "F125W_KRON_S_e": ("nJy", "NMAD uncertainty of source flux within aperture R_KRON_S, measured from a series of random apertures"),
    "F125W_SEG_e": ("nJy", "NMAD uncertainty of source flux within aperture SEG, measured from a series of random apertures"),
    "F140W_KRON_e": ("nJy", "NMAD uncertainty of source flux within aperture R_KRON, measured from a series of random apertures"),
    "F140W_KRON_S_e": ("nJy", "NMAD uncertainty of source flux within aperture R_KRON_S, measured from a series of random apertures"),
    "F140W_SEG_e": ("nJy", "NMAD uncertainty of source flux within aperture SEG, measured from a series of random apertures"),
    "F160W_KRON_e": ("nJy", "NMAD uncertainty of source flux within aperture R_KRON, measured from a series of random apertures"),
    "F160W_KRON_S_e": ("nJy", "NMAD uncertainty of source flux within aperture R_KRON_S, measured from a series of random apertures"),
    "F160W_SEG_e": ("nJy", "NMAD uncertainty of source flux within aperture SEG, measured from a series of random apertures"),
},
}

tables = []

for hdu, columns in columns_hdu.items():
    tab = apTab.Table.read(filename, hdu=hdu)[list(columns.keys())]
    for colname, (unit, desc) in columns.items():
        tab[colname].unit = u.Unit(unit)
        tab[colname].description = desc
    tables.append(tab)

tab_ap = apTab.hstack(tables)

coords = [
    SpherePoint(ra, dec, degrees) for ra, dec in zip(tab_ap["RA"], tab_ap["DEC"])
]
within = np.array([tractInfo.contains(coord) for coord in coords])
if np.sum(within) != len(within):
    tab_ap = tab_ap[within]
    coords = [coord for coord, in_tract in zip(coords, within) if in_tract]
patches = np.array(
    [tractInfo.findPatch(coord).getSequentialIndex() for coord in coords],
    dtype=np.int16,
)
tab_ap["patch"] = patches
tab_ap["patch"].description = f"{skymap} patch index"

tab_arrow = astropy_to_arrow(tab_ap)
row_group_size = compute_row_group_size(tab_arrow.schema)

pq.write_table(tab_arrow, f"{name_tab}.parq", row_group_size=row_group_size)
