import astropy.table as apTab
import astropy.units as u
import numpy as np
from lsst.daf.butler.formatters.parquet import astropy_to_arrow, compute_row_group_size
import pyarrow.parquet as pq

# from https://datalab.noirlab.edu/query.php?name=des_dr1.y3_gold
# downloaded in nine chunks because the whole query didn't work
# ra: 52.14077598745257, 54.03427611473381 (1.89)

# dec: -28.35063896360024, -27.8, -27.25, -26.684313552983653 (1.666)
# (dec >= -27.25) AND (dec < -26.684313552983653)

# select * from des_dr2.y6_gold WHERE (ra > 52.14077598745257) AND (ra < 54.03427611473381) #
# AND (dec > -28.35063896360024) AND (dec < -26.684313552983653)

name_tab = "des_y6gold_lsst_cells_v1_5063"

tab_ap = apTab.Table.read(f"{name_tab}.csv")
# I can't figure out how to specify csv with commented header
tab_ap.rename_columns(("# a_fiducial_g",), ("a_fiducial_g",))

columns = (
    ("bdf_mag_err_z", "mag", "double", "Uncertainty on BDF_MAG_Z"),
    ("moly_number_g", "", "double", "Unique identifier of the MOLYGON that this object resides in."),
    ("a_fiducial_g", "mag", "double", "SED-independent interstellar extinction based on the E(B - V) reddening maps from Schlegel, Finkbeiner & Davis (1998) in band g"),
    ("a_fiducial_i", "mag", "double", "SED-independent interstellar extinction based on the E(B - V) reddening maps from Schlegel, Finkbeiner & Davis (1998) in band i"),
    ("a_fiducial_r", "mag", "double", "SED-independent interstellar extinction based on the E(B - V) reddening maps from Schlegel, Finkbeiner & Davis (1998) in band r"),
    ("a_fiducial_y", "mag", "double", "SED-independent interstellar extinction based on the E(B - V) reddening maps from Schlegel, Finkbeiner & Davis (1998) in band Y"),
    ("a_fiducial_z", "mag", "double", "SED-independent interstellar extinction based on the E(B - V) reddening maps from Schlegel, Finkbeiner & Davis (1998) in band z"),
    ("a_image", "pixels", "double", "Detection image based basic shape parameter; A = semimajor-axis"),
    ("alphawin_j2000", "deg", "double", "Right Ascension (J2000.0) of the object using a Gaussian window with a FWHM corresponding to the disk containing 50% of the flux"),
    ("b_image", "pixels", "double", "Detection image based basic shape parameter; B = semiminor-axis"),
    ("badpix_frac", "", "double", "Fraction of pixels in the FITVD fitting region labelled as bad"),
    ("bdf_deblend_flags", "", "int", "Shredder deblend flag bits: 1 no deblend, 2 PSF fit failed, 4 initial deblend on coadd failed, 8 multi-fit deblend failed"),
    ("bdf_flags", "", "short", "BDF fit flags"),
    ("bdf_flux_cov_1_1", "(3.63 nJy)^2", "double", "Diagonal variance on the BDF flux g band"),
    ("bdf_flux_cov_1_2", "(3.63 nJy)^2", "double", "Off-diagonal variance on the BDF flux difference in (g-r)"),
    ("bdf_flux_cov_1_3", "(3.63 nJy)^2", "double", "Off-diagonal variance on the BDF flux difference in (g-i)"),
    ("bdf_flux_cov_1_4", "(3.63 nJy)^2", "double", "Off-diagonal variance on the BDF flux difference in (g-z)"),
    ("bdf_flux_cov_1_5", "(3.63 nJy)^2", "double", "Off-diagonal variance on the BDF flux difference in (g-Y)"),
    ("bdf_flux_cov_2_1", "(3.63 nJy)^2", "double", "Off-diagonal variance on the BDF flux difference in (r-g)"),
    ("bdf_flux_cov_2_2", "(3.63 nJy)^2", "double", "Diagonal variance on the BDF flux r band"),
    ("bdf_flux_cov_2_3", "(3.63 nJy)^2", "double", "Off-diagonal variance on the BDF flux difference in (r-i)"),
    ("bdf_flux_cov_2_4", "(3.63 nJy)^2", "double", "Off-diagonal variance on the BDF flux difference in (r-z)"),
    ("bdf_flux_cov_2_5", "(3.63 nJy)^2", "double", "Off-diagonal variance on the BDF flux difference in (r-Y)"),
    ("bdf_flux_cov_3_1", "(3.63 nJy)^2", "double", "Off-diagonal variance on the BDF flux difference in (i-g)"),
    ("bdf_flux_cov_3_2", "(3.63 nJy)^2", "double", "Off-diagonal variance on the BDF flux difference in (i-r)"),
    ("bdf_flux_cov_3_3", "(3.63 nJy)^2", "double", "Diagonal variance on the BDF flux i band"),
    ("bdf_flux_cov_3_4", "(3.63 nJy)^2", "double", "Off-diagonal variance on the BDF flux difference in (i-z)"),
    ("bdf_flux_cov_3_5", "(3.63 nJy)^2", "double", "Off-diagonal variance on the BDF flux difference in (i-Y)"),
    ("bdf_flux_cov_4_1", "(3.63 nJy)^2", "double", "Off-diagonal variance on the BDF flux difference in (z-g)"),
    ("bdf_flux_cov_4_2", "(3.63 nJy)^2", "double", "Off-diagonal variance on the BDF flux difference in (z-r)"),
    ("bdf_flux_cov_4_3", "(3.63 nJy)^2", "double", "Off-diagonal variance on the BDF flux difference in (z-i)"),
    ("bdf_flux_cov_4_4", "(3.63 nJy)^2", "double", "Diagonal variance on the BDF flux z band"),
    ("bdf_flux_cov_4_5", "(3.63 nJy)^2", "double", "Off-diagonal variance on the BDF flux difference in (z-Y)"),
    ("bdf_flux_cov_5_1", "(3.63 nJy)^2", "double", "Off-diagonal variance on the BDF flux difference in (Y-g)"),
    ("bdf_flux_cov_5_2", "(3.63 nJy)^2", "double", "Off-diagonal variance on the BDF flux difference in (Y-r)"),
    ("bdf_flux_cov_5_3", "(3.63 nJy)^2", "double", "Off-diagonal variance on the BDF flux difference in (Y-i)"),
    ("bdf_flux_cov_5_4", "(3.63 nJy)^2", "double", "Off-diagonal variance on the BDF flux difference in (Y-z)"),
    ("bdf_flux_cov_5_5", "(3.63 nJy)^2", "double", "Diagonal variance on the BDF flux Y band"),
    ("bdf_flux_err_g", "3.63 nJy", "double", "Uncertainty on BDF_FLUX_G"),
    ("bdf_flux_err_g_corrected", "3.63 nJy", "double", "Uncertainty on BDF_FLUX_CORRECTED_G"),
    ("bdf_flux_err_i", "3.63 nJy", "double", "Uncertainty on BDF_FLUX_I"),
    ("bdf_flux_err_i_corrected", "3.63 nJy", "double", "Uncertainty on BDF_FLUX_CORRECTED_I"),
    ("bdf_flux_err_r", "3.63 nJy", "double", "Uncertainty on BDF_FLUX_R"),
    ("bdf_flux_err_r_corrected", "3.63 nJy", "double", "Uncertainty on BDF_FLUX_CORRECTED_R"),
    ("bdf_flux_err_y", "3.63 nJy", "double", "Uncertainty on BDF_FLUX_Y"),
    ("bdf_flux_err_y_corrected", "3.63 nJy", "double", "Uncertainty on BDF_FLUX_CORRECTED_Y"),
    ("bdf_flux_err_z", "3.63 nJy", "double", "Uncertainty on BDF_FLUX_Z"),
    ("bdf_flux_err_z_corrected", "3.63 nJy", "double", "Uncertainty on BDF_FLUX_CORRECTED_Z"),
    ("bdf_flux_g", "3.63 nJy", "double", "Flux derived with BDF model in g-band. No aperture correction, top of atmosphere."),
    ("bdf_flux_g_corrected", "3.63 nJy", "double", "BDF_FLUX_G corrected for interstellar extinction (i.e. de-reddened; top of Galaxy) and PSF aperture ratio (APER8 system)."),
    ("bdf_flux_i", "3.63 nJy", "double", "Flux derived with BDF model in i-band. No aperture correction, top of atmosphere."),
    ("bdf_flux_i_corrected", "3.63 nJy", "double", "BDF_FLUX_I corrected for interstellar extinction (i.e. de-reddened; top of Galaxy) and PSF aperture ratio (APER8 system)."),
    ("bdf_flux_r", "3.63 nJy", "double", "Flux derived with BDF model in r-band. No aperture correction, top of atmosphere."),
    ("bdf_flux_r_corrected", "3.63 nJy", "double", "BDF_FLUX_R corrected for interstellar extinction (i.e. de-reddened; top of Galaxy) and PSF aperture ratio (APER8 system)."),
    ("bdf_flux_y", "3.63 nJy", "double", "Flux derived with BDF model in Y-band. No aperture correction, top of atmosphere."),
    ("bdf_flux_y_corrected", "3.63 nJy", "double", "BDF_FLUX_Y corrected for interstellar extinction (i.e. de-reddened; top of Galaxy) and PSF aperture ratio (APER8 system)."),
    ("bdf_flux_z", "3.63 nJy", "double", "Flux derived with BDF model in z-band. No aperture correction, top of atmosphere."),
    ("bdf_flux_z_corrected", "3.63 nJy", "double", "BDF_FLUX_Z corrected for interstellar extinction (i.e. de-reddened; top of Galaxy) and PSF aperture ratio (APER8 system)."),
    ("bdf_fracdev", "", "double", "Fraction assigned to De Vaucouleurs profile in composite model."),
    ("bdf_fracdev_err", "", "double", "Uncertainty on BDF_FRACDEV"),
    ("bdf_g_1", "", "double", "First component of gamma giving axis ratio and position angle of ellipse fit"),
    ("bdf_g_2", "", "double", "Second component of gamma giving axis ratio and position angle of ellipse fit"),
    ("bdf_g_cov_1_1", "", "double", "Covariance of gamma 1,2 axis ratio and position angle components (1,1) term"),
    ("bdf_g_cov_1_2", "", "double", "Covariance of gamma 1,2 axis ratio and position angle components (1,2) term"),
    ("bdf_g_cov_2_1", "", "double", "Covariance of gamma 1,2 axis ratio and position angle components (2,1) term"),
    ("bdf_g_cov_2_2", "", "double", "Covariance of gamma 1,2 axis ratio and position angle components (2,2) term"),
    ("bdf_gmr_err", "mag", "double", "Uncertainty on g-r color, accounting for covariance"),
    ("bdf_imz_err", "", "double", "Uncertainty on i-z color, accounting for covariance"),
    ("bdf_mag_err_g", "mag", "double", "Uncertainty on BDF_MAG_G"),
    ("bdf_mag_err_i", "mag", "double", "Uncertainty on BDF_MAG_I"),
    ("bdf_mag_err_r", "mag", "double", "Uncertainty on BDF_MAG_R"),
    ("bdf_mag_err_y", "mag", "double", "Uncertainty on BDF_MAG_Y"),
    ("bdf_mag_g", "mag", "double", "Magnitude measured by FITVD BDF model in g-band. No aperture correction, top of atmosphere"),
    ("bdf_mag_g_corrected", "mag", "double", "BDF_MAG corrected for interstellar extinction (de-reddened top of Galaxy) and PSF aperture ratio (APER8 system)"),
    ("bdf_mag_i", "mag", "double", "Magnitude measured by FITVD BDF model in i-band. No aperture correction, top of atmosphere"),
    ("bdf_mag_i_corrected", "mag", "double", "BDF_MAG corrected for interstellar extinction (de-reddened top of Galaxy) and PSF aperture ratio (APER8 system)"),
    ("bdf_mag_r", "mag", "double", "Magnitude measured by FITVD BDF model in r-band. No aperture correction, top of atmosphere"),
    ("bdf_mag_r_corrected", "mag", "double", "BDF_MAG corrected for interstellar extinction (de-reddened top of Galaxy) and PSF aperture ratio (APER8 system)"),
    ("bdf_mag_y", "mag", "double", "Magnitude measured by FITVD BDF model in Y-band. No aperture correction, top of atmosphere"),
    ("bdf_mag_y_corrected", "mag", "double", "BDF_MAG corrected for interstellar extinction (de-reddened top of Galaxy) and PSF aperture ratio (APER8 system)"),
    ("bdf_mag_z", "mag", "double", "Magnitude measured by FITVD BDF model in z-band. No aperture correction, top of atmosphere"),
    ("bdf_mag_z_corrected", "mag", "double", "BDF_MAG corrected for interstellar extinction (de-reddened top of Galaxy) and PSF aperture ratio (APER8 system)"),
    ("bdf_nfev", "", "int", "Number of function evaluations during BDF fit."),
    ("bdf_ntry", "", "short", "Number of times the fit was attempted."),
    ("bdf_pars_1", "arcsec", "double", "BDF fit parameter 1: row-offset fit position of object in MEDs postage stamp"),
    ("bdf_pars_2", "arcsec", "double", "BDF fit parameter 2: col-offset fit position of object in MEDs postage stamp"),
    ("bdf_pars_err_1", "arcsec", "double", "Error on x-offset"),
    ("bdf_pars_err_2", "arcsec", "double", "Error on y-offset"),
    ("bdf_rmi_err", "mag", "double", "Uncertainty on r-i color, accounting for covariance"),
    ("bdf_s2n", "", "double", "Signal-to-noise on BDF fit, combining all bands"),
    ("bdf_t", "arcsec^2", "double", "Intrinsic squared size of best-fit BDF model, before PSF convolution"),
    ("bdf_t_err", "arcsec^2", "double", "Uncertainty on BDF_T"),
    ("bdf_t_ratio", "", "double", "Ratio of BDF_T of the object to PSF_T at the location of the object (stars are near zero)."),
    ("bdf_zmy_err", "mag", "double", "Uncertainty on z-Y color, accounting for covariance"),
    ("coadd_object_id", "", "int", "Unique identifier for the coadded objects"),
    ("conc", "", "double", "Concentration index -- values near 0 indicate stellar object, significantly above 0 extended"),
    ("conc_flags", "", "short", "Flag for CONC index fit failure (0 = success; 1 = failure)"),
    ("coverfrac_griz", "", "double", "Fractional area of HEALPix (nside=4096) pixel covered simultaneously by griz bands"),
    ("coverfrac_grizy", "", "double", "Fractional area of HEALPix (nside=4096) pixel covered simultaneously by grizY bands"),
    ("coverfrac_riz", "", "double", "Fractional area of HEALPix (nside=4096) pixel covered simultaneously by riz bands"),
    ("coverfrac_rizy", "", "double", "Fractional area of HEALPix (nside=4096) pixel covered simultaneously by rizY bands"),
    ("dec", "deg", "double", "Declination (J2000.0) with quantized precision for indexing (DELTAWIN_J2000 has full precision but not indexed)"),
    ("deltawin_j2000", "deg", "double", "Declination (J2000.0) of the object using a Gaussian window with a FWHM corresponding to the disk containing 50% of the flux"),
    ("dnf_d1", "", "double", "DNF photo-z photometric directional distance to nearest neighbor."),
    ("dnf_de1", "", "double", "DNF photo-z photometric Euclidean distance to nearest neighbor."),
    ("dnf_id1", "", "int", "DNF photo-z COADD_OBJECT_ID corresponding to the nearest neighbor in the training sample."),
    ("dnf_nneighbors", "", "float", "DNF photo-z number of neighbors used for the DNF_Z estimate"),
    ("dnf_z", "", "double", "DNF photo-z primary point estimate obtained by fitting to the directional neighborhood. Useful for clasification in tomographic bins."),
    ("dnf_zerr_fit", "", "double", "DNF photo-z error term derived from the residuals of the regression fit"),
    ("dnf_zerr_param", "", "double", "DNF photo-z error term due to magnitude/flux uncertainties propagation"),
    ("dnf_zn", "", "double", "DNF photo-z nearest neighbor spec-z. Useful for estimating N(z) for a given sample."),
    ("dnf_zsigma", "", "double", "DNF photo-z uncertainty estimate from photometric uncertainties and residuals from the neighborhood fit"),
    ("ebv_sfd98", "", "double", "E(B-V) reddening coefficient from Schlegel, Finkbeiner & Davis (1998)"),
    ("elat", "deg", "double", "Ecliptic latitude"),
    ("elon", "deg", "double", "Ecliptic longitude"),
    ("erra_image", "pixel", "double", "Uncertainty in major axis size, from isophotal model"),
    ("errb_image", "pixel", "double", "Uncertainty in minor axis size, from isophotal model"),
    ("errtheta_image", "deg", "double", "Uncertainty in source position, from isophotal model"),
    ("ext_coadd", "", "short", "Extended object classification from coadd SourceExtractor measurements. 0: high-confidence stars; 1: candidate stars; 2: mostly galaxies; 3: high-confidence galaxies; -9: No data"),
    ("ext_fitvd", "", "short", "Extended object classification from FITVD multi-epoch fit. 0: high-confidence stars; 1: candidate stars; 2: mostly galaxies; 3: high confidence galaxies; 4: pure galaxy sample; -9: No data"),
    ("ext_mash", "", "short", "Extended object classification combined for COADD, WAVG, and FITVD. 0: high-confidence stars; 1: candidate stars; 2: mostly galaxies; 3: high confidence galaxies; 4: pure galaxy sample; -9: No data"),
    ("ext_wavg", "", "short", "Extended object classification from WAVG single-epoch measurements. 0: high-confidence stars; 1: candidate stars; 2: mostly galaxies; 3: high-confidence galaxies; -9: No data"),
    ("ext_xgb", "", "short", "Extended object classification based on XGBoost morphological classifier: 0: high-confidence stars; 1: candidate stars; 2: mostly galaxies; 3: high confidence galaxies; 4: pure galaxy sample; -9: No data"),
    ("fitvd_flags", "", "short", "Flag for FITVD BDF fit failure (0=success, 1=failure)"),
    ("flags_footprint", "", "short", "Flag describing whether the object is contained in the fiducial footprint of the survey. See Sevilla-Noarbe et al. (2021) for description"),
    ("flags_foreground", "", "short", "Flag describing whether the object is contained in a region with a foreground astrophysical object. See Sevilla-Noarbe et al. (2021) for description."),
    ("flags_gold", "", "short", "Flag describing object anomalies. See Sevilla-Noarbe et al. (2021) for description."),
    ("flagstr", "", "char[14]", "Brief description of BDF quality flag. See Section 3.4 of Bechtol et al. (2025)"),
    ("flux_radius_g", "pixel", "double", "Half-light radius for the object, from elliptical growth-curve, modeled in 2 dimensions, in g band"),
    ("flux_radius_i", "pixel", "double", "Half-light radius for the object, from elliptical growth-curve, modeled in 2 dimensions, in i band"),
    ("flux_radius_r", "pixel", "double", "Half-light radius for the object, from elliptical growth-curve, modeled in 2 dimensions, in r band"),
    ("flux_radius_y", "pixel", "double", "Half-light radius for the object, from elliptical growth-curve, modeled in 2 dimensions, in Y band"),
    ("flux_radius_z", "pixel", "double", "Half-light radius for the object, from elliptical growth-curve, modeled in 2 dimensions, in z band"),
    ("fof_id", "", "int", "Friends-of-friends shredder group ID number"),
    ("fof_size", "", "short", "Friends-of-friends shredder group size"),
    ("gap_flux_err_g", "3.63 nJy", "double", "Uncertainty on Gaussian aperture flux"),
    ("gap_flux_err_i", "3.63 nJy", "double", "Uncertainty on Gaussian aperture flux"),
    ("gap_flux_err_r", "3.63 nJy", "double", "Uncertainty on Gaussian aperture flux"),
    ("gap_flux_err_y", "3.63 nJy", "double", "Uncertainty on Gaussian aperture flux"),
    ("gap_flux_err_z", "3.63 nJy", "double", "Uncertainty on Gaussian aperture flux"),
    ("gap_flux_g", "3.63 nJy", "double", "Gaussian Aperture fluxes with FWHM=4 arcsec"),
    ("gap_flux_i", "3.63 nJy", "double", "Gaussian Aperture fluxes with FWHM=4 arcsec"),
    ("gap_flux_r", "3.63 nJy", "double", "Gaussian Aperture fluxes with FWHM=4 arcsec"),
    ("gap_flux_y", "3.63 nJy", "double", "Gaussian Aperture fluxes with FWHM=4 arcsec"),
    ("gap_flux_z", "3.63 nJy", "double", "Gaussian Aperture fluxes with FWHM=4 arcsec"),
    ("gap_mag_err_g", "mag", "double", "Uncertainty on Gaussian aperture magnitude"),
    ("gap_mag_err_i", "mag", "double", "Uncertainty on Gaussian aperture magnitude"),
    ("gap_mag_err_r", "mag", "double", "Uncertainty on Gaussian aperture magnitude"),
    ("gap_mag_err_y", "mag", "double", "Uncertainty on Gaussian aperture magnitude"),
    ("gap_mag_err_z", "mag", "double", "Uncertainty on Gaussian aperture magnitude"),
    ("gap_mag_g", "mag", "double", "Magnitude measured by Gaussian aperture fit"),
    ("gap_mag_i", "mag", "double", "Magnitude measured by Gaussian aperture fit"),
    ("gap_mag_r", "mag", "double", "Magnitude measured by Gaussian aperture fit"),
    ("gap_mag_y", "mag", "double", "Magnitude measured by Gaussian aperture fit"),
    ("gap_mag_z", "mag", "double", "Magnitude measured by Gaussian aperture fit"),
    ("glat", "deg", "double", "Galactic latitude"),
    ("glon", "deg", "double", "Galactic longitude"),
    ("hpix_1024", "", "int", "Healpix index for NSIDE = 1024 in NEST schema for the object"),
    ("hpix_16384", "", "long", "Healpix index for NSIDE = 16384 in NEST schema for the object"),
    ("hpix_32", "", "short", "Healpix index for NSIDE = 32 in NEST schema for the object"),
    ("hpix_4096", "", "int", "Healpix index for NSIDE = 4096 in NEST schema for the object"),
    ("hpix_64", "", "int", "Healpix index for NSIDE = 64 in NEST schema for the object"),
    ("htm9", "", "int", "Ninth level (~10 arcmin resolution) Hierarchical Triangular Mesh index (Szalay et al. 2007)"),
    ("imaflags_iso_g", "", "short", "Flag identifying sources with missing/flagged pixels, considering all single epoch images, in g band"),
    ("imaflags_iso_i", "", "short", "Flag identifying sources with missing/flagged pixels, considering all single epoch images, in i band"),
    ("imaflags_iso_r", "", "short", "Flag identifying sources with missing/flagged pixels, considering all single epoch images, in r band"),
    ("imaflags_iso_y", "", "short", "Flag identifying sources with missing/flagged pixels, considering all single epoch images, in Y band"),
    ("imaflags_iso_z", "", "short", "Flag identifying sources with missing/flagged pixels, considering all single epoch images, in z band"),
    ("kron_radius", "", "double", "Detection image luminosity weighted radius for the object, encompassing approximately 90% of the total flux"),
    ("mag_aper_4_g", "mag", "double", "Magnitude measured in circular aperture with 1.9488 arcsec diameter"),
    ("mag_aper_4_i", "mag", "double", "Magnitude measured in circular aperture with 1.9488 arcsec diameter"),
    ("mag_aper_4_r", "mag", "double", "Magnitude measured in circular aperture with 1.9488 arcsec diameter"),
    ("mag_aper_4_y", "mag", "double", "Magnitude measured in circular aperture with 1.9488 arcsec diameter"),
    ("mag_aper_4_z", "mag", "double", "Magnitude measured in circular aperture with 1.9488 arcsec diameter"),
    ("mag_aper_8_g", "mag", "double", "Magnitude measured in a circular aperture of 22.22 pixels (5.8437 arcsecs) diameter, g band"),
    ("mag_aper_8_i", "mag", "double", "Magnitude measured in a circular aperture of 22.22 pixels (5.8437 arcsecs) diameter, i band"),
    ("mag_aper_8_r", "mag", "double", "Magnitude measured in a circular aperture of 22.22 pixels (5.8437 arcsecs) diameter, r band"),
    ("mag_aper_8_y", "mag", "double", "Magnitude measured in a circular aperture of 22.22 pixels (5.8437 arcsecs) diameter, Y band"),
    ("mag_aper_8_z", "mag", "double", "Magnitude measured in a circular aperture of 22.22 pixels (5.8437 arcsecs) diameter, z band"),
    ("mag_auto_g", "mag", "double", "Magnitude measurement in an elliptical aperture, shaped by the second moments of the object and scaled by the Kron radius, g band"),
    ("mag_auto_i", "mag", "double", "Magnitude measurement in an elliptical aperture, shaped by the second moments of the object and scaled by the Kron radius, i band"),
    ("mag_auto_r", "mag", "double", "Magnitude measurement in an elliptical aperture, shaped by the second moments of the object and scaled by the Kron radius, r band"),
    ("mag_auto_y", "mag", "double", "Magnitude measurement in an elliptical aperture, shaped by the second moments of the object and scaled by the Kron radius, Y band"),
    ("mag_auto_z", "mag", "double", "Magnitude measurement in an elliptical aperture, shaped by the second moments of the object and scaled by the Kron radius, z band"),
    ("mag_detmodel_g", "mag", "double", "Magnitude measurement, for a bulge + disk model fit on the detection image, g band"),
    ("mag_detmodel_i", "mag", "double", "Magnitude measurement, for a bulge + disk model fit on the detection image, i band"),
    ("mag_detmodel_r", "mag", "double", "Magnitude measurement, for a bulge + disk model fit on the detection image, r band"),
    ("mag_detmodel_y", "mag", "double", "Magnitude measurement, for a bulge + disk model fit on the detection image, Y band"),
    ("mag_detmodel_z", "mag", "double", "Magnitude measurement, for a bulge + disk model fit on the detection image, z band"),
    ("magerr_aper_4_g", "mag", "double", "Uncertainty in MAG_APER_4_G"),
    ("magerr_aper_4_i", "mag", "double", "Uncertainty in MAG_APER_4_I"),
    ("magerr_aper_4_r", "mag", "double", "Uncertainty in MAG_APER_4_R"),
    ("magerr_aper_4_y", "mag", "double", "Uncertainty in MAG_APER_4_Y"),
    ("magerr_aper_4_z", "mag", "double", "Uncertainty in MAG_APER_4_Z"),
    ("magerr_aper_8_g", "mag", "double", "Error in MAG_APER_8_G, scaled from FLUXERR_APER_8"),
    ("magerr_aper_8_i", "mag", "double", "Error in MAG_APER_8_I, scaled from FLUXERR_APER_8"),
    ("magerr_aper_8_r", "mag", "double", "Error in MAG_APER_8_R, scaled from FLUXERR_APER_8"),
    ("magerr_aper_8_y", "mag", "double", "Error in MAG_APER_8_Y, scaled from FLUXERR_APER_8"),
    ("magerr_aper_8_z", "mag", "double", "Error in MAG_APER_8_Z, scaled from FLUXERR_APER_8"),
    ("magerr_auto_g", "mag", "double", "Error in MAG_AUTO_G, scaled from FLUXERR_AUTO"),
    ("magerr_auto_i", "mag", "double", "Error in MAG_AUTO_I, scaled from FLUXERR_AUTO"),
    ("magerr_auto_r", "mag", "double", "Error in MAG_AUTO_R, scaled from FLUXERR_AUTO"),
    ("magerr_auto_y", "mag", "double", "Error in MAG_AUTO_Y, scaled from FLUXERR_AUTO"),
    ("magerr_auto_z", "mag", "double", "Error in MAG_AUTO_Z, scaled from FLUXERR_AUTO"),
    ("magerr_detmodel_g", "mag", "double", "Error in MAG_DETMODEL_G, scaled from FLUXERR_DETMODEL"),
    ("magerr_detmodel_i", "mag", "double", "Error in MAG_DETMODEL_I, scaled from FLUXERR_DETMODEL"),
    ("magerr_detmodel_r", "mag", "double", "Error in MAG_DETMODEL_R, scaled from FLUXERR_DETMODEL"),
    ("magerr_detmodel_y", "mag", "double", "Error in MAG_DETMODEL_Y, scaled from FLUXERR_DETMODEL"),
    ("magerr_detmodel_z", "mag", "double", "Error in MAG_DETMODEL_Z, scaled from FLUXERR_DETMODEL"),
    ("mask_flags", "", "short", "Flag indicating the object was masked, e.g. due to bright star masking"),
    ("moly_number_i", "", "double", "Unique identifier of the MOLYGON that this object resides in."),
    ("moly_number_r", "", "double", "Unique identifier of the MOLYGON that this object resides in."),
    ("moly_number_y", "", "double", "Unique identifier of the MOLYGON that this object resides in."),
    ("moly_number_z", "", "double", "Unique identifier of the MOLYGON that this object resides in."),
    ("mu_eff_model_g", "mag./sq.arcsec", "double", "Effective model surface brightness above background. The surface brightness is measured at the isophote which includes half of the flux of the model, above background, in g band"),
    ("mu_eff_model_i", "mag./sq.arcsec", "double", "Effective model surface brightness above background. The surface brightness is measured at the isophote which includes half of the flux of the model, above background, in i band"),
    ("mu_eff_model_r", "mag./sq.arcsec", "double", "Effective model surface brightness above background. The surface brightness is measured at the isophote which includes half of the flux of the model, above background, in r band"),
    ("mu_eff_model_y", "mag./sq.arcsec", "double", "Effective model surface brightness above background. The surface brightness is measured at the isophote which includes half of the flux of the model, above background, in Y band"),
    ("mu_eff_model_z", "mag./sq.arcsec", "double", "Effective model surface brightness above background. The surface brightness is measured at the isophote which includes half of the flux of the model, above background, in z band"),
    ("mu_max_g", "mag./sq.arcsec", "double", "Surface brightness at the brightest pixel in g band"),
    ("mu_max_i", "mag./sq.arcsec", "double", "Surface brightness at the brightest pixel in i band"),
    ("mu_max_model_g", "mag./sq.arcsec", "double", "Maximum surface brightness in g band using the whole area inside the isophote used for MU_EFF_MODEL_G"),
    ("mu_max_model_i", "mag./sq.arcsec", "double", "Maximum surface brightness in i band using the whole area inside the isophote used for MU_EFF_MODEL_I"),
    ("mu_max_model_r", "mag./sq.arcsec", "double", "Maximum surface brightness in r band using the whole area inside the isophote used for MU_EFF_MODEL_R"),
    ("mu_max_model_y", "mag./sq.arcsec", "double", "Maximum surface brightness in Y band using the whole area inside the isophote used for MU_EFF_MODEL_Y"),
    ("mu_max_model_z", "mag./sq.arcsec", "double", "Maximum surface brightness in z band using the whole area inside the isophote used for MU_EFF_MODEL_Z"),
    ("mu_max_r", "mag./sq.arcsec", "double", "Surface brightness at the brightest pixel in r band"),
    ("mu_max_y", "mag./sq.arcsec", "double", "Surface brightness at the brightest pixel in Y band"),
    ("mu_max_z", "mag./sq.arcsec", "double", "Surface brightness at the brightest pixel in z band"),
    ("mu_mean_model_g", "mag./sq.arcsec", "double", "Mean surface brightness in g band using the whole area inside the isophote used for MU_EFF_MODEL_G"),
    ("mu_mean_model_i", "mag./sq.arcsec", "double", "Mean surface brightness in i band using the whole area inside the isophote used for MU_EFF_MODEL_I"),
    ("mu_mean_model_r", "mag./sq.arcsec", "double", "Mean surface brightness in r band using the whole area inside the isophote used for MU_EFF_MODEL_R"),
    ("mu_mean_model_y", "mag./sq.arcsec", "double", "Mean surface brightness in Y band using the whole area inside the isophote used for MU_EFF_MODEL_Y"),
    ("mu_mean_model_z", "mag./sq.arcsec", "double", "Mean surface brightness in z band using the whole area inside the isophote used for MU_EFF_MODEL_Z"),
    ("mu_threshold_g", "mag./sq.arcsec", "double", "Surface brightness threshold (SExtractor parameter) in g band"),
    ("mu_threshold_i", "mag./sq.arcsec", "double", "Surface brightness threshold (SExtractor parameter) in i band"),
    ("mu_threshold_r", "mag./sq.arcsec", "double", "Surface brightness threshold (SExtractor parameter) in r band"),
    ("mu_threshold_y", "mag./sq.arcsec", "double", "Surface brightness threshold (SExtractor parameter) in Y band"),
    ("mu_threshold_z", "mag./sq.arcsec", "double", "Surface brightness threshold (SExtractor parameter) in z band"),
    ("n_images_g", "", "double", "Number of g band exposures at the object location (from the Healpix map)"),
    ("n_images_i", "", "double", "Number of i band exposures at the object location (from the Healpix map)"),
    ("n_images_r", "", "double", "Number of r band exposures at the object location (from the Healpix map)"),
    ("n_images_y", "", "double", "Number of Y band exposures at the object location (from the Healpix map)"),
    ("n_images_z", "", "double", "Number of z band exposures at the object location (from the Healpix map)"),
    ("nepochs_g", "", "short", "Number of epochs the source is detected in single epoch images"),
    ("nepochs_i", "", "short", "Number of epochs the source is detected in single epoch images"),
    ("nepochs_r", "", "short", "Number of epochs the source is detected in single epoch images"),
    ("nepochs_y", "", "short", "Number of epochs the source is detected in single epoch images"),
    ("nepochs_z", "", "short", "Number of epochs the source is detected in single epoch images"),
    ("niter_model_g", "", "short", "Number of iterations for convergence in SExtractor model fitting"),
    ("niter_model_i", "", "short", "Number of iterations for convergence in SExtractor model fitting"),
    ("niter_model_r", "", "short", "Number of iterations for convergence in SExtractor model fitting"),
    ("niter_model_y", "", "short", "Number of iterations for convergence in SExtractor model fitting"),
    ("niter_model_z", "", "short", "Number of iterations for convergence in SExtractor model fitting"),
    ("object_number", "", "int", "SExtractor unique number for a processing tile"),
    ("parent_number", "", "int", "SExtractor OBJECT_NUMBER of parent object of which this object is a deblended child"),
    ("pfw_attempt_id", "", "int", "DESDM internal processing index number"),
    ("psf_flux_aper_8_g", "3.63 nJy", "double", "Flux measured by FITVD PSF model in APER8 system (reddened, top of atmosphere)"),
    ("psf_flux_aper_8_i", "3.63 nJy", "double", "Flux measured by FITVD PSF model in APER8 system (reddened, top of atmosphere)"),
    ("psf_flux_aper_8_r", "3.63 nJy", "double", "Flux measured by FITVD PSF model in APER8 system (reddened, top of atmosphere)"),
    ("psf_flux_aper_8_y", "3.63 nJy", "double", "Flux measured by FITVD PSF model in APER8 system (reddened, top of atmosphere)"),
    ("psf_flux_aper_8_z", "3.63 nJy", "double", "Flux measured by FITVD PSF model in APER8 system (reddened, top of atmosphere)"),
    ("psf_flux_err_aper_8_g", "3.63 nJy", "double", "Uncertainty on PSF_FLUX_APER_8_G"),
    ("psf_flux_err_aper_8_i", "3.63 nJy", "double", "Uncertainty on PSF_FLUX_APER_8_I"),
    ("psf_flux_err_aper_8_r", "3.63 nJy", "double", "Uncertainty on PSF_FLUX_APER_8_R"),
    ("psf_flux_err_aper_8_y", "3.63 nJy", "double", "Uncertainty on PSF_FLUX_APER_8_Y"),
    ("psf_flux_err_aper_8_z", "3.63 nJy", "double", "Uncertainty on PSF_FLUX_APER_8_Z"),
    ("psf_flux_flags_g", "", "short", "Flags for FITVD PSF flux measurement: 0=success, 1=bad variance, 512=divide by zero, 1024=degrees of freedom are zero"),
    ("psf_flux_flags_i", "", "short", "Flags for FITVD PSF flux measurement: 0=success, 1=bad variance, 512=divide by zero, 1024=degrees of freedom are zero"),
    ("psf_flux_flags_r", "", "short", "Flags for FITVD PSF flux measurement: 0=success, 1=bad variance, 512=divide by zero, 1024=degrees of freedom are zero"),
    ("psf_flux_flags_y", "", "short", "Flags for FITVD PSF flux measurement: 0=success, 1=bad variance, 512=divide by zero, 1024=degrees of freedom are zero"),
    ("psf_flux_flags_z", "", "short", "Flags for FITVD PSF flux measurement: 0=success, 1=bad variance, 512=divide by zero, 1024=degrees of freedom are zero"),
    ("psf_flux_ratio_aper_8_g", "", "double", "PSF aperture correction to put BDF corrected magnitudes onto FGCM photometric system"),
    ("psf_flux_ratio_aper_8_i", "", "double", "PSF aperture correction to put BDF corrected magnitudes onto FGCM photometric system"),
    ("psf_flux_ratio_aper_8_r", "", "double", "PSF aperture correction to put BDF corrected magnitudes onto FGCM photometric system"),
    ("psf_flux_ratio_aper_8_y", "", "double", "PSF aperture correction to put BDF corrected magnitudes onto FGCM photometric system"),
    ("psf_flux_ratio_aper_8_z", "", "double", "PSF aperture correction to put BDF corrected magnitudes onto FGCM photometric system"),
    ("psf_flux_s2n_aper_8_g", "", "double", "S/N in PSF flux measurement from FITVD in APER8 system"),
    ("psf_flux_s2n_aper_8_i", "", "double", "S/N in PSF flux measurement from FITVD in APER8 system"),
    ("psf_flux_s2n_aper_8_r", "", "double", "S/N in PSF flux measurement from FITVD in APER8 system"),
    ("psf_flux_s2n_aper_8_y", "", "double", "S/N in PSF flux measurement from FITVD in APER8 system"),
    ("psf_flux_s2n_aper_8_z", "", "double", "S/N in PSF flux measurement from FITVD in APER8 system"),
    ("psf_g_1", "", "double", "Ellipticity of the multi-Gaussian model fit to the PSF (component 1) at the location of the object"),
    ("psf_g_2", "", "double", "Ellipticity of the multi-Gaussian model fit to the PSF (component 2) at the location of the object"),
    ("psf_mag_aper_8_g", "mag", "double", "Magnitude measured by FITVD PSF model in APER8 system (reddened top of atmosphere)"),
    ("psf_mag_aper_8_g_corrected", "mag", "double", "Magnitude measured by FITVD PSF model corrected for interstellar extinction (de-reddened top of Galaxy) and PSF aperture ratio (APER8 system). Recommended for point-source studies."),
    ("psf_mag_aper_8_i", "mag", "double", "Magnitude measured by FITVD PSF model in APER8 system (reddened top of atmosphere)"),
    ("psf_mag_aper_8_i_corrected", "mag", "double", "Magnitude measured by FITVD PSF model corrected for interstellar extinction (de-reddened top of Galaxy) and PSF aperture ratio (APER8 system). Recommended for point-source studies."),
    ("psf_mag_aper_8_r", "mag", "double", "Magnitude measured by FITVD PSF model in APER8 system (reddened top of atmosphere)"),
    ("psf_mag_aper_8_r_corrected", "mag", "double", "Magnitude measured by FITVD PSF model corrected for interstellar extinction (de-reddened top of Galaxy) and PSF aperture ratio (APER8 system). Recommended for point-source studies."),
    ("psf_mag_aper_8_y", "mag", "double", "Magnitude measured by FITVD PSF model in APER8 system (reddened top of atmosphere)"),
    ("psf_mag_aper_8_y_corrected", "mag", "double", "Magnitude measured by FITVD PSF model corrected for interstellar extinction (de-reddened top of Galaxy) and PSF aperture ratio (APER8 system). Recommended for point-source studies."),
    ("psf_mag_aper_8_z", "mag", "double", "Magnitude measured by FITVD PSF model in APER8 system (reddened top of atmosphere)"),
    ("psf_mag_aper_8_z_corrected", "mag", "double", "Magnitude measured by FITVD PSF model corrected for interstellar extinction (de-reddened top of Galaxy) and PSF aperture ratio (APER8 system). Recommended for point-source studies."),
    ("psf_mag_err_aper_8_g", "mag", "double", "Uncertainty in PSF_MAG_APER_8_G"),
    ("psf_mag_err_aper_8_i", "mag", "double", "Uncertainty in PSF_MAG_APER_8_I"),
    ("psf_mag_err_aper_8_r", "mag", "double", "Uncertainty in PSF_MAG_APER_8_R"),
    ("psf_mag_err_aper_8_y", "mag", "double", "Uncertainty in PSF_MAG_APER_8_Y"),
    ("psf_mag_err_aper_8_z", "mag", "double", "Uncertainty in PSF_MAG_APER_8_Z"),
    ("psf_t", "arcsec^2", "double", "Squared-size for a multi-Gaussian model fit to the PSF at the location of the object"),
    ("ra", "deg", "double", "Right Ascension (J2000.0) with quantized precision for indexing (ALPHAWIN_J2000 has full precision but not indexed)"),
    ("random_id", "", "float", "Random ID in the range 0.0 => 100.0"),
    ("ring256", "", "int", "Ring-scheme HEALPix (Gorski et al. 2005) index with NSIDE=256 (~14 arcmin resolution)"),
    ("s_extractor_flags_g", "", "short", "SExtractor 16-bit flag parameter which contains basic warnings about the source extraction process"),
    ("s_extractor_flags_i", "", "short", "SExtractor 16-bit flag parameter which contains basic warnings about the source extraction process"),
    ("s_extractor_flags_r", "", "short", "SExtractor 16-bit flag parameter which contains basic warnings about the source extraction process"),
    ("s_extractor_flags_y", "", "short", "SExtractor 16-bit flag parameter which contains basic warnings about the source extraction process"),
    ("s_extractor_flags_z", "", "short", "SExtractor 16-bit flag parameter which contains basic warnings about the source extraction process"),
    ("spread_model_g", "", "double", "Morphology based classifier based on a linear discriminant between the pixel map of the object convolved with the PSF model and the pixel map convolved with a PSF+exponential model. Values closer to 0 correspond to stars, larger values correspond to galaxies"),
    ("spread_model_i", "", "double", "Morphology based classifier based on a linear discriminant between the pixel map of the object convolved with the PSF model and the pixel map convolved with a PSF+exponential model. Values closer to 0 correspond to stars, larger values correspond to galaxies"),
    ("spread_model_r", "", "double", "Morphology based classifier based on a linear discriminant between the pixel map of the object convolved with the PSF model and the pixel map convolved with a PSF+exponential model. Values closer to 0 correspond to stars, larger values correspond to galaxies"),
    ("spread_model_y", "", "double", "Morphology based classifier based on a linear discriminant between the pixel map of the object convolved with the PSF model and the pixel map convolved with a PSF+exponential model. Values closer to 0 correspond to stars, larger values correspond to galaxies"),
    ("spread_model_z", "", "double", "Morphology based classifier based on a linear discriminant between the pixel map of the object convolved with the PSF model and the pixel map convolved with a PSF+exponential model. Values closer to 0 correspond to stars, larger values correspond to galaxies"),
    ("spreaderr_model_g", "", "double", "Uncertainty in SPREAD_MODEL_G"),
    ("spreaderr_model_i", "", "double", "Uncertainty in SPREAD_MODEL_I"),
    ("spreaderr_model_r", "", "double", "Uncertainty in SPREAD_MODEL_R"),
    ("spreaderr_model_y", "", "double", "Uncertainty in SPREAD_MODEL_Y"),
    ("spreaderr_model_z", "", "double", "Uncertainty in SPREAD_MODEL_Z"),
    ("theta_j2000", "deg", "double", "Position angle of the ellipse fit to the object with the N/S/E/W axes in equatorial J2000 coordinates, from non-windowed measurement. THETA_J2000 = THETA_IMAGE-90(MOD 180)"),
    ("tilename", "", "char[12]", "Identifier of each one of the tiles on which the survey is gridded for data processing"),
    ("wavg_mag_psf_g", "mag", "double", "Magnitude measured by weighted-average of PSF fit to single-epoch detections"),
    ("wavg_mag_psf_i", "mag", "double", "Magnitude measured by weighted-average of PSF fit to single-epoch detections"),
    ("wavg_mag_psf_r", "mag", "double", "Magnitude measured by weighted-average of PSF fit to single-epoch detections"),
    ("wavg_mag_psf_y", "mag", "double", "Magnitude measured by weighted-average of PSF fit to single-epoch detections"),
    ("wavg_mag_psf_z", "mag", "double", "Magnitude measured by weighted-average of PSF fit to single-epoch detections"),
    ("wavg_magerr_psf_g", "mag", "double", "Uncertainty in WAVG_MAG_PSF_G"),
    ("wavg_magerr_psf_i", "mag", "double", "Uncertainty in WAVG_MAG_PSF_I"),
    ("wavg_magerr_psf_r", "mag", "double", "Uncertainty in WAVG_MAG_PSF_R"),
    ("wavg_magerr_psf_y", "mag", "double", "Uncertainty in WAVG_MAG_PSF_Y"),
    ("wavg_magerr_psf_z", "mag", "double", "Uncertainty in WAVG_MAG_PSF_Z"),
    ("wavg_spread_model_g", "", "double", "SPREAD MODEL using the weighted averaged values from single epoch detections"),
    ("wavg_spread_model_i", "", "double", "SPREAD MODEL using the weighted averaged values from single epoch detections"),
    ("wavg_spread_model_r", "", "double", "SPREAD MODEL using the weighted averaged values from single epoch detections"),
    ("wavg_spread_model_y", "", "double", "SPREAD MODEL using the weighted averaged values from single epoch detections"),
    ("wavg_spread_model_z", "", "double", "SPREAD MODEL using the weighted averaged values from single epoch detections"),
    ("wavg_spreaderr_model_g", "", "double", "Uncertainty in WAVG_SPREAD_MODEL_G"),
    ("wavg_spreaderr_model_i", "", "double", "Uncertainty in WAVG_SPREAD_MODEL_I"),
    ("wavg_spreaderr_model_r", "", "double", "Uncertainty in WAVG_SPREAD_MODEL_R"),
    ("wavg_spreaderr_model_y", "", "double", "Uncertainty in WAVG_SPREAD_MODEL_Y"),
    ("wavg_spreaderr_model_z", "", "double", "Uncertainty in WAVG_SPREAD_MODEL_Z"),
    ("xgb_pred", "", "double", "Output pseudo-probability of the XGBoost star/galaxy classifer. Galaxies have XGB_PRED ~ 0 and stars have XGB_PRED ~ 1. See Section 4.2 of Bechtol et al. (2025)."),
    ("xwin_image", "pixel", "double", "X position of the barycenter of the object within the image using a Gaussian window with a FWHM corresponding to the radius of the aperture containing 50% of the flux"),
    ("ywin_image", "pixel", "double", "Y position of the barycenter of the object within the image using a Gaussian window with a FWHM corresponding to the radius of the aperture containing 50% of the flux"),
)

units = {
    # The schema seems to be incorrect - these are picomaggies like DR1
    # (30 mag zeropoint is 3.630780547701 nJy, not 3.63)
    "3.63 nJy": "3.630780547701002891614 nJy",
    "(3.63 nJy)^2": "13.182567385563993767 nJy2",
    "mag./sq.arcsec": "mag/arcsec^2",
    "pixels": "pix",
}

for values in columns:
    if len(values) != 4:
        print(f"{values[0]} len={len(values)}")
        continue
    name, unit, dtype, desc = values
    if name in tab_ap.colnames:
        column = tab_ap[name]
        if dtype.startswith("char"):
            print(f"{dtype=} vs {column.dtype=}")
        else:
            dtype_spec = np.dtype(dtype)
            if column.dtype != dtype_spec:
                try:
                    # This seems to change the dtype without changing
                    # anything in memory and does bad things to ints
                    # column.dtype = dtype_spec
                    tab_ap[name] = tab_ap[name].astype(dtype_spec)
                except Exception as e:
                    print(f"Couldn't set {name=} dtype to {dtype_spec=} due to:\n{e}")
                print(f"{name} {column.dtype=} != {dtype=}")

        unit_new = units.get(unit, unit)
        unit_obj = u.Unit(unit_new)
        if unit_obj.is_equivalent(u.nJy):
            column *= (unit_obj/u.nJy).scale
            unit_new = u.nJy
        elif unit_obj.is_equivalent(u.nJy**2):
            column *= (unit_obj / u.nJy**2).scale
            unit_new = u.nJy**2

        column.unit = unit_new
        column.description = desc
    else:
        print(f"{name} column not found")

# This catalog doesn't seem to have RA/dec errors
# The BDF fits have errors on the x/y centroids (which hopefully are RA/dec)
# Add a systematic term and a maximum error (some are huge)
bdf_cen_err_sys_asec = 1e-3
bdf_cen_err_max_asec = 1.0

for col_in, col_out, desc in (
    ("bdf_pars_err_1", "ra_err", "Right Ascension"),
    ("bdf_pars_err_2", "dec_err", "Declination"),
):
    tab_ap[col_out] = np.clip(
        np.sqrt(tab_ap[col_in]**2 + bdf_cen_err_sys_asec**2), 0, bdf_cen_err_max_asec
    ).to(u.degree)
    tab_ap[col_out].description = (f'{desc} error, estimated as clip(sqrt({col_in}**2 + '
                                   f'{bdf_cen_err_sys_asec}"**2), 0", 1"')

tab_arrow = astropy_to_arrow(tab_ap)
row_group_size = compute_row_group_size(tab_arrow.schema)

pq.write_table(tab_arrow, f"{name_tab}.parq")
