import astropy.table as apTab
import astropy.units as u
import lsst.daf.butler as dafButler
from lsst.daf.butler.formatters.parquet import astropy_to_arrow, compute_row_group_size
from lsst.geom import degrees, SpherePoint
import numpy as np
import pyarrow.parquet as pq

skymap = "lsst_cells_v2"
tract = 5063
name_tab = "hlsp_jades_jwst_nircam_goods-s_photometry_v5.0_catalog"
filename = f"{name_tab}.fits"
butler = dafButler.Butler("dp2_prep", collections="skymaps")
tractInfo = butler.get("skyMap", skymap=skymap)[tract]

columns_hdu = {
2: {
    "ID": ("", "Unique ID of source"),
    "RA": ("deg", "RA of source, ICRS, from detection image"),
    "DEC": ("deg", "Dec of source, ICRS, from detection image"),
    "F090W_FLAG": ("", "Number of bad pixels in band"),
    "F115W_FLAG": ("", "Number of bad pixels in band"),
    "F150W_FLAG": ("", "Number of bad pixels in band"),
    "F182M_FLAG": ("", "Number of bad pixels in band"),
    "F200W_FLAG": ("", "Number of bad pixels in band"),
    "F210M_FLAG": ("", "Number of bad pixels in band"),
    "F277W_FLAG": ("", "Number of bad pixels in band"),
    "F335M_FLAG": ("", "Number of bad pixels in band"),
    "F356W_FLAG": ("", "Number of bad pixels in band"),
    "F410M_FLAG": ("", "Number of bad pixels in band"),
    "F430M_FLAG": ("", "Number of bad pixels in band"),
    "F444W_FLAG": ("", "Number of bad pixels in band"),
    "F460M_FLAG": ("", "Number of bad pixels in band"),
    "F480M_FLAG": ("", "Number of bad pixels in band"),
    "F435W_FLAG": ("", "Number of bad pixels in band"),
    "F606W_FLAG": ("", "Number of bad pixels in band"),
    "F775W_FLAG": ("", "Number of bad pixels in band"),
    "F814W_FLAG": ("", "Number of bad pixels in band"),
    "F850LP_FLAG": ("", "Number of bad pixels in band"),
    "F105W_FLAG": ("", "Number of bad pixels in band"),
    "F125W_FLAG": ("", "Number of bad pixels in band"),
    "F140W_FLAG": ("", "Number of bad pixels in band"),
    "F160W_FLAG": ("", "Number of bad pixels in band"),
    "F090W_TEXP": ("s", "Average exposure time in band"),
    "F115W_TEXP": ("s", "Average exposure time in band"),
    "F150W_TEXP": ("s", "Average exposure time in band"),
    "F182M_TEXP": ("s", "Average exposure time in band"),
    "F200W_TEXP": ("s", "Average exposure time in band"),
    "F210M_TEXP": ("s", "Average exposure time in band"),
    "F277W_TEXP": ("s", "Average exposure time in band"),
    "F335M_TEXP": ("s", "Average exposure time in band"),
    "F356W_TEXP": ("s", "Average exposure time in band"),
    "F410M_TEXP": ("s", "Average exposure time in band"),
    "F430M_TEXP": ("s", "Average exposure time in band"),
    "F444W_TEXP": ("s", "Average exposure time in band"),
    "F460M_TEXP": ("s", "Average exposure time in band"),
    "F480M_TEXP": ("s", "Average exposure time in band"),
    "F435W_TEXP": ("s", "Average exposure time in band"),
    "F606W_TEXP": ("s", "Average exposure time in band"),
    "F775W_TEXP": ("s", "Average exposure time in band"),
    "F814W_TEXP": ("s", "Average exposure time in band"),
    "F850LP_TEXP": ("s", "Average exposure time in band"),
    "F105W_TEXP": ("s", "Average exposure time in band"),
    "F125W_TEXP": ("s", "Average exposure time in band"),
    "F140W_TEXP": ("s", "Average exposure time in band"),
    "F160W_TEXP": ("s", "Average exposure time in band"),
    "F090W_WHT": ("", "Average weight in band"),
    "F115W_WHT": ("", "Average weight in band"),
    "F150W_WHT": ("", "Average weight in band"),
    "F182M_WHT": ("", "Average weight in band"),
    "F200W_WHT": ("", "Average weight in band"),
    "F210M_WHT": ("", "Average weight in band"),
    "F277W_WHT": ("", "Average weight in band"),
    "F335M_WHT": ("", "Average weight in band"),
    "F356W_WHT": ("", "Average weight in band"),
    "F410M_WHT": ("", "Average weight in band"),
    "F430M_WHT": ("", "Average weight in band"),
    "F444W_WHT": ("", "Average weight in band"),
    "F460M_WHT": ("", "Average weight in band"),
    "F480M_WHT": ("", "Average weight in band"),
    "F435W_WHT": ("", "Average weight in band"),
    "F606W_WHT": ("", "Average weight in band"),
    "F775W_WHT": ("", "Average weight in band"),
    "F814W_WHT": ("", "Average weight in band"),
    "F850LP_WHT": ("", "Average weight in band"),
    "F105W_WHT": ("", "Average weight in band"),
    "F125W_WHT": ("", "Average weight in band"),
    "F140W_WHT": ("", "Average weight in band"),
    "F160W_WHT": ("", "Average weight in band"),
    "FLAG_BN": ("", "0 default, 1 if neighbor >2x brighter, 2 if neighbor >10x brighter"),
},
3: {
    "NPIX_DET": ("", "Number of pixels in the detection image belonging to the object"),
    "X": ("pix", "x-centroid in detection image, windowed"),
    "Y": ("pix", "y-centroid in detection image, windowed"),
    "XC": ("pix", "x-centroid in detection image, barycenter"),
    "YC": ("pix", "y-centroid in detection image, barycenter"),
    "BBOX_XMIN": ("pix", "Bounding box x-minimum in detection image"),
    "BBOX_XMAX": ("pix", "Bounding box x-maximum in detection image"),
    "BBOX_YMIN": ("pix", "Bounding box y-minimum in detection image"),
    "BBOX_YMAX": ("pix", "Bounding box y-maximum in detection image"),
    "R_KRON_U": ("arcsec", "Kron radius with Kron parameter 2.5, from detection image"),
    "A": ("arcsec", "Semi-major axis length, from detection image"),
    "B": ("arcsec", "Semi-minor axis length, from detection image"),
    "FWHM": ("arcsec", "Circular-equivalent full width half max"),
    "THETA": ("deg", "Position angle"),
    "GINI": ("", "Gini coefficient (concentration)"),
},
5: {
    "F070W_CIRC0": ("nJy", ""),
    "F070W_CIRC0_bkg": ("nJy", ""),
    "F070W_CIRC0_e": ("nJy", ""),
    "F070W_CIRC0_ei": ("nJy", ""),
    "F070W_CIRC1": ("nJy", ""),
    "F070W_CIRC1_bkg": ("nJy", ""),
    "F070W_CIRC1_e": ("nJy", ""),
    "F070W_CIRC1_ei": ("nJy", ""),
    "F070W_CIRC2": ("nJy", ""),
    "F070W_CIRC2_bkg": ("nJy", ""),
    "F070W_CIRC2_e": ("nJy", ""),
    "F070W_CIRC2_ei": ("nJy", ""),
    "F070W_CIRC3": ("nJy", ""),
    "F070W_CIRC3_bkg": ("nJy", ""),
    "F070W_CIRC3_e": ("nJy", ""),
    "F070W_CIRC3_ei": ("nJy", ""),
    "F070W_CIRC4": ("nJy", ""),
    "F070W_CIRC4_bkg": ("nJy", ""),
    "F070W_CIRC4_e": ("nJy", ""),
    "F070W_CIRC4_ei": ("nJy", ""),
    "F070W_CIRC5": ("nJy", ""),
    "F070W_CIRC5_bkg": ("nJy", ""),
    "F070W_CIRC5_e": ("nJy", ""),
    "F070W_CIRC5_ei": ("nJy", ""),
    "F070W_CIRC6": ("nJy", ""),
    "F070W_CIRC6_bkg": ("nJy", ""),
    "F070W_CIRC6_e": ("nJy", ""),
    "F070W_CIRC6_ei": ("nJy", ""),
    "F090W_CIRC0": ("nJy", ""),
    "F090W_CIRC0_bkg": ("nJy", ""),
    "F090W_CIRC0_e": ("nJy", ""),
    "F090W_CIRC0_ei": ("nJy", ""),
    "F090W_CIRC1": ("nJy", ""),
    "F090W_CIRC1_bkg": ("nJy", ""),
    "F090W_CIRC1_e": ("nJy", ""),
    "F090W_CIRC1_ei": ("nJy", ""),
    "F090W_CIRC2": ("nJy", ""),
    "F090W_CIRC2_bkg": ("nJy", ""),
    "F090W_CIRC2_e": ("nJy", ""),
    "F090W_CIRC2_ei": ("nJy", ""),
    "F090W_CIRC3": ("nJy", ""),
    "F090W_CIRC3_bkg": ("nJy", ""),
    "F090W_CIRC3_e": ("nJy", ""),
    "F090W_CIRC3_ei": ("nJy", ""),
    "F090W_CIRC4": ("nJy", ""),
    "F090W_CIRC4_bkg": ("nJy", ""),
    "F090W_CIRC4_e": ("nJy", ""),
    "F090W_CIRC4_ei": ("nJy", ""),
    "F090W_CIRC5": ("nJy", ""),
    "F090W_CIRC5_bkg": ("nJy", ""),
    "F090W_CIRC5_e": ("nJy", ""),
    "F090W_CIRC5_ei": ("nJy", ""),
    "F090W_CIRC6": ("nJy", ""),
    "F090W_CIRC6_bkg": ("nJy", ""),
    "F090W_CIRC6_e": ("nJy", ""),
    "F090W_CIRC6_ei": ("nJy", ""),
    "F105W_CIRC0": ("nJy", ""),
    "F105W_CIRC0_bkg": ("nJy", ""),
    "F105W_CIRC0_e": ("nJy", ""),
    "F105W_CIRC0_ei": ("nJy", ""),
    "F105W_CIRC1": ("nJy", ""),
    "F105W_CIRC1_bkg": ("nJy", ""),
    "F105W_CIRC1_e": ("nJy", ""),
    "F105W_CIRC1_ei": ("nJy", ""),
    "F105W_CIRC2": ("nJy", ""),
    "F105W_CIRC2_bkg": ("nJy", ""),
    "F105W_CIRC2_e": ("nJy", ""),
    "F105W_CIRC2_ei": ("nJy", ""),
    "F105W_CIRC3": ("nJy", ""),
    "F105W_CIRC3_bkg": ("nJy", ""),
    "F105W_CIRC3_e": ("nJy", ""),
    "F105W_CIRC3_ei": ("nJy", ""),
    "F105W_CIRC4": ("nJy", ""),
    "F105W_CIRC4_bkg": ("nJy", ""),
    "F105W_CIRC4_e": ("nJy", ""),
    "F105W_CIRC4_ei": ("nJy", ""),
    "F105W_CIRC5": ("nJy", ""),
    "F105W_CIRC5_bkg": ("nJy", ""),
    "F105W_CIRC5_e": ("nJy", ""),
    "F105W_CIRC5_ei": ("nJy", ""),
    "F105W_CIRC6": ("nJy", ""),
    "F105W_CIRC6_bkg": ("nJy", ""),
    "F105W_CIRC6_e": ("nJy", ""),
    "F105W_CIRC6_ei": ("nJy", ""),
    "F115W_CIRC0": ("nJy", ""),
    "F115W_CIRC0_bkg": ("nJy", ""),
    "F115W_CIRC0_e": ("nJy", ""),
    "F115W_CIRC0_ei": ("nJy", ""),
    "F115W_CIRC1": ("nJy", ""),
    "F115W_CIRC1_bkg": ("nJy", ""),
    "F115W_CIRC1_e": ("nJy", ""),
    "F115W_CIRC1_ei": ("nJy", ""),
    "F115W_CIRC2": ("nJy", ""),
    "F115W_CIRC2_bkg": ("nJy", ""),
    "F115W_CIRC2_e": ("nJy", ""),
    "F115W_CIRC2_ei": ("nJy", ""),
    "F115W_CIRC3": ("nJy", ""),
    "F115W_CIRC3_bkg": ("nJy", ""),
    "F115W_CIRC3_e": ("nJy", ""),
    "F115W_CIRC3_ei": ("nJy", ""),
    "F115W_CIRC4": ("nJy", ""),
    "F115W_CIRC4_bkg": ("nJy", ""),
    "F115W_CIRC4_e": ("nJy", ""),
    "F115W_CIRC4_ei": ("nJy", ""),
    "F115W_CIRC5": ("nJy", ""),
    "F115W_CIRC5_bkg": ("nJy", ""),
    "F115W_CIRC5_e": ("nJy", ""),
    "F115W_CIRC5_ei": ("nJy", ""),
    "F115W_CIRC6": ("nJy", ""),
    "F115W_CIRC6_bkg": ("nJy", ""),
    "F115W_CIRC6_e": ("nJy", ""),
    "F115W_CIRC6_ei": ("nJy", ""),
    "F606W_CIRC0": ("nJy", ""),
    "F606W_CIRC0_bkg": ("nJy", ""),
    "F606W_CIRC0_e": ("nJy", ""),
    "F606W_CIRC0_ei": ("nJy", ""),
    "F606W_CIRC1": ("nJy", ""),
    "F606W_CIRC1_bkg": ("nJy", ""),
    "F606W_CIRC1_e": ("nJy", ""),
    "F606W_CIRC1_ei": ("nJy", ""),
    "F606W_CIRC2": ("nJy", ""),
    "F606W_CIRC2_bkg": ("nJy", ""),
    "F606W_CIRC2_e": ("nJy", ""),
    "F606W_CIRC2_ei": ("nJy", ""),
    "F606W_CIRC3": ("nJy", ""),
    "F606W_CIRC3_bkg": ("nJy", ""),
    "F606W_CIRC3_e": ("nJy", ""),
    "F606W_CIRC3_ei": ("nJy", ""),
    "F606W_CIRC4": ("nJy", ""),
    "F606W_CIRC4_bkg": ("nJy", ""),
    "F606W_CIRC4_e": ("nJy", ""),
    "F606W_CIRC4_ei": ("nJy", ""),
    "F606W_CIRC5": ("nJy", ""),
    "F606W_CIRC5_bkg": ("nJy", ""),
    "F606W_CIRC5_e": ("nJy", ""),
    "F606W_CIRC5_ei": ("nJy", ""),
    "F606W_CIRC6": ("nJy", ""),
    "F606W_CIRC6_bkg": ("nJy", ""),
    "F606W_CIRC6_e": ("nJy", ""),
    "F606W_CIRC6_ei": ("nJy", ""),
    "F775W_CIRC0": ("nJy", ""),
    "F775W_CIRC0_bkg": ("nJy", ""),
    "F775W_CIRC0_e": ("nJy", ""),
    "F775W_CIRC0_ei": ("nJy", ""),
    "F775W_CIRC1": ("nJy", ""),
    "F775W_CIRC1_bkg": ("nJy", ""),
    "F775W_CIRC1_e": ("nJy", ""),
    "F775W_CIRC1_ei": ("nJy", ""),
    "F775W_CIRC2": ("nJy", ""),
    "F775W_CIRC2_bkg": ("nJy", ""),
    "F775W_CIRC2_e": ("nJy", ""),
    "F775W_CIRC2_ei": ("nJy", ""),
    "F775W_CIRC3": ("nJy", ""),
    "F775W_CIRC3_bkg": ("nJy", ""),
    "F775W_CIRC3_e": ("nJy", ""),
    "F775W_CIRC3_ei": ("nJy", ""),
    "F775W_CIRC4": ("nJy", ""),
    "F775W_CIRC4_bkg": ("nJy", ""),
    "F775W_CIRC4_e": ("nJy", ""),
    "F775W_CIRC4_ei": ("nJy", ""),
    "F775W_CIRC5": ("nJy", ""),
    "F775W_CIRC5_bkg": ("nJy", ""),
    "F775W_CIRC5_e": ("nJy", ""),
    "F775W_CIRC5_ei": ("nJy", ""),
    "F775W_CIRC6": ("nJy", ""),
    "F775W_CIRC6_bkg": ("nJy", ""),
    "F775W_CIRC6_e": ("nJy", ""),
    "F775W_CIRC6_ei": ("nJy", ""),
    "F814W_CIRC0": ("nJy", ""),
    "F814W_CIRC0_bkg": ("nJy", ""),
    "F814W_CIRC0_e": ("nJy", ""),
    "F814W_CIRC0_ei": ("nJy", ""),
    "F814W_CIRC1": ("nJy", ""),
    "F814W_CIRC1_bkg": ("nJy", ""),
    "F814W_CIRC1_e": ("nJy", ""),
    "F814W_CIRC1_ei": ("nJy", ""),
    "F814W_CIRC2": ("nJy", ""),
    "F814W_CIRC2_bkg": ("nJy", ""),
    "F814W_CIRC2_e": ("nJy", ""),
    "F814W_CIRC2_ei": ("nJy", ""),
    "F814W_CIRC3": ("nJy", ""),
    "F814W_CIRC3_bkg": ("nJy", ""),
    "F814W_CIRC3_e": ("nJy", ""),
    "F814W_CIRC3_ei": ("nJy", ""),
    "F814W_CIRC4": ("nJy", ""),
    "F814W_CIRC4_bkg": ("nJy", ""),
    "F814W_CIRC4_e": ("nJy", ""),
    "F814W_CIRC4_ei": ("nJy", ""),
    "F814W_CIRC5": ("nJy", ""),
    "F814W_CIRC5_bkg": ("nJy", ""),
    "F814W_CIRC5_e": ("nJy", ""),
    "F814W_CIRC5_ei": ("nJy", ""),
    "F814W_CIRC6": ("nJy", ""),
    "F814W_CIRC6_bkg": ("nJy", ""),
    "F814W_CIRC6_e": ("nJy", ""),
    "F814W_CIRC6_ei": ("nJy", ""),
},
8: {
    "A_KRON": ("arcsec", "Semi-major axis length (KRON)"),
    "B_KRON": ("arcsec", "Semi-minor axis length (KRON)"),
    "THETA_KRON": ("deg", "Position angle (KRON)"),
    "A_KRON_S": ("arcsec", "Semi-major axis length (KRON_S)"),
    "B_KRON_S": ("arcsec", "Semi-minor axis length (KRON_S)"),
    "THETA_KRON_S": ("deg", "Position angle (KRON_S)"),
    "F070W_KRON": ("nJy", "Flux of source in band within aperture R_KRON"),
    "F070W_KRON_S": ("nJy", "Flux of source in band within aperture R_KRON_S"),
    "F090W_KRON": ("nJy", "Flux of source in band within aperture R_KRON"),
    "F090W_KRON_S": ("nJy", "Flux of source in band within aperture R_KRON_S"),
    "F115W_KRON": ("nJy", "Flux of source in band within aperture R_KRON"),
    "F115W_KRON_S": ("nJy", "Flux of source in band within aperture R_KRON_S"),
    "F150W_KRON": ("nJy", "Flux of source in band within aperture R_KRON"),
    "F150W_KRON_S": ("nJy", "Flux of source in band within aperture R_KRON_S"),
    "F182M_KRON": ("nJy", "Flux of source in band within aperture R_KRON"),
    "F182M_KRON_S": ("nJy", "Flux of source in band within aperture R_KRON_S"),
    "F200W_KRON": ("nJy", "Flux of source in band within aperture R_KRON"),
    "F200W_KRON_S": ("nJy", "Flux of source in band within aperture R_KRON_S"),
    "F210M_KRON": ("nJy", "Flux of source in band within aperture R_KRON"),
    "F210M_KRON_S": ("nJy", "Flux of source in band within aperture R_KRON_S"),
    "F277W_KRON": ("nJy", "Flux of source in band within aperture R_KRON"),
    "F277W_KRON_S": ("nJy", "Flux of source in band within aperture R_KRON_S"),
    "F335M_KRON": ("nJy", "Flux of source in band within aperture R_KRON"),
    "F335M_KRON_S": ("nJy", "Flux of source in band within aperture R_KRON_S"),
    "F356W_KRON": ("nJy", "Flux of source in band within aperture R_KRON"),
    "F356W_KRON_S": ("nJy", "Flux of source in band within aperture R_KRON_S"),
    "F410M_KRON": ("nJy", "Flux of source in band within aperture R_KRON"),
    "F410M_KRON_S": ("nJy", "Flux of source in band within aperture R_KRON_S"),
    "F430M_KRON": ("nJy", "Flux of source in band within aperture R_KRON"),
    "F430M_KRON_S": ("nJy", "Flux of source in band within aperture R_KRON_S"),
    "F444W_KRON": ("nJy", "Flux of source in band within aperture R_KRON"),
    "F444W_KRON_S": ("nJy", "Flux of source in band within aperture R_KRON_S"),
    "F460M_KRON": ("nJy", "Flux of source in band within aperture R_KRON"),
    "F460M_KRON_S": ("nJy", "Flux of source in band within aperture R_KRON_S"),
    "F480M_KRON": ("nJy", "Flux of source in band within aperture R_KRON"),
    "F480M_KRON_S": ("nJy", "Flux of source in band within aperture R_KRON_S"),
    "F435W_KRON": ("nJy", "Flux of source in band within aperture R_KRON"),
    "F435W_KRON_S": ("nJy", "Flux of source in band within aperture R_KRON_S"),
    "F606W_KRON": ("nJy", "Flux of source in band within aperture R_KRON"),
    "F606W_KRON_S": ("nJy", "Flux of source in band within aperture R_KRON_S"),
    "F775W_KRON": ("nJy", "Flux of source in band within aperture R_KRON"),
    "F775W_KRON_S": ("nJy", "Flux of source in band within aperture R_KRON_S"),
    "F814W_KRON": ("nJy", "Flux of source in band within aperture R_KRON"),
    "F814W_KRON_S": ("nJy", "Flux of source in band within aperture R_KRON_S"),
    "F850LP_KRON": ("nJy", "Flux of source in band within aperture R_KRON"),
    "F850LP_KRON_S": ("nJy", "Flux of source in band within aperture R_KRON_S"),
    "F105W_KRON": ("nJy", "Flux of source in band within aperture R_KRON"),
    "F105W_KRON_S": ("nJy", "Flux of source in band within aperture R_KRON_S"),
    "F125W_KRON": ("nJy", "Flux of source in band within aperture R_KRON"),
    "F125W_KRON_S": ("nJy", "Flux of source in band within aperture R_KRON_S"),
    "F140W_KRON": ("nJy", "Flux of source in band within aperture R_KRON"),
    "F140W_KRON_S": ("nJy", "Flux of source in band within aperture R_KRON_S"),
    "F160W_KRON": ("nJy", "Flux of source in band within aperture R_KRON"),
    "F160W_KRON_S": ("nJy", "Flux of source in band within aperture R_KRON_S"),
    "F070W_KRON_ei": ("nJy", "Uncertainty of source flux within aperture R_KRON, measured from the ERR extension"),
    "F070W_KRON_S_ei": ("nJy", "Uncertainty of source flux within aperture R_KRON_S, measured from the ERR extension"),
    "F090W_KRON_ei": ("nJy", "Uncertainty of source flux within aperture R_KRON, measured from the ERR extension"),
    "F090W_KRON_S_ei": ("nJy", "Uncertainty of source flux within aperture R_KRON_S, measured from the ERR extension"),
    "F115W_KRON_ei": ("nJy", "Uncertainty of source flux within aperture R_KRON, measured from the ERR extension"),
    "F115W_KRON_S_ei": ("nJy", "Uncertainty of source flux within aperture R_KRON_S, measured from the ERR extension"),
    "F150W_KRON_ei": ("nJy", "Uncertainty of source flux within aperture R_KRON, measured from the ERR extension"),
    "F150W_KRON_S_ei": ("nJy", "Uncertainty of source flux within aperture R_KRON_S, measured from the ERR extension"),
    "F182M_KRON_ei": ("nJy", "Uncertainty of source flux within aperture R_KRON, measured from the ERR extension"),
    "F182M_KRON_S_ei": ("nJy", "Uncertainty of source flux within aperture R_KRON_S, measured from the ERR extension"),
    "F200W_KRON_ei": ("nJy", "Uncertainty of source flux within aperture R_KRON, measured from the ERR extension"),
    "F200W_KRON_S_ei": ("nJy", "Uncertainty of source flux within aperture R_KRON_S, measured from the ERR extension"),
    "F210M_KRON_ei": ("nJy", "Uncertainty of source flux within aperture R_KRON, measured from the ERR extension"),
    "F210M_KRON_S_ei": ("nJy", "Uncertainty of source flux within aperture R_KRON_S, measured from the ERR extension"),
    "F277W_KRON_ei": ("nJy", "Uncertainty of source flux within aperture R_KRON, measured from the ERR extension"),
    "F277W_KRON_S_ei": ("nJy", "Uncertainty of source flux within aperture R_KRON_S, measured from the ERR extension"),
    "F335M_KRON_ei": ("nJy", "Uncertainty of source flux within aperture R_KRON, measured from the ERR extension"),
    "F335M_KRON_S_ei": ("nJy", "Uncertainty of source flux within aperture R_KRON_S, measured from the ERR extension"),
    "F356W_KRON_ei": ("nJy", "Uncertainty of source flux within aperture R_KRON, measured from the ERR extension"),
    "F356W_KRON_S_ei": ("nJy", "Uncertainty of source flux within aperture R_KRON_S, measured from the ERR extension"),
    "F410M_KRON_ei": ("nJy", "Uncertainty of source flux within aperture R_KRON, measured from the ERR extension"),
    "F410M_KRON_S_ei": ("nJy", "Uncertainty of source flux within aperture R_KRON_S, measured from the ERR extension"),
    "F430M_KRON_ei": ("nJy", "Uncertainty of source flux within aperture R_KRON, measured from the ERR extension"),
    "F430M_KRON_S_ei": ("nJy", "Uncertainty of source flux within aperture R_KRON_S, measured from the ERR extension"),
    "F444W_KRON_ei": ("nJy", "Uncertainty of source flux within aperture R_KRON, measured from the ERR extension"),
    "F444W_KRON_S_ei": ("nJy", "Uncertainty of source flux within aperture R_KRON_S, measured from the ERR extension"),
    "F460M_KRON_ei": ("nJy", "Uncertainty of source flux within aperture R_KRON, measured from the ERR extension"),
    "F460M_KRON_S_ei": ("nJy", "Uncertainty of source flux within aperture R_KRON_S, measured from the ERR extension"),
    "F480M_KRON_ei": ("nJy", "Uncertainty of source flux within aperture R_KRON, measured from the ERR extension"),
    "F480M_KRON_S_ei": ("nJy", "Uncertainty of source flux within aperture R_KRON_S, measured from the ERR extension"),
    "F435W_KRON_ei": ("nJy", "Uncertainty of source flux within aperture R_KRON, measured from the ERR extension"),
    "F435W_KRON_S_ei": ("nJy", "Uncertainty of source flux within aperture R_KRON_S, measured from the ERR extension"),
    "F606W_KRON_ei": ("nJy", "Uncertainty of source flux within aperture R_KRON, measured from the ERR extension"),
    "F606W_KRON_S_ei": ("nJy", "Uncertainty of source flux within aperture R_KRON_S, measured from the ERR extension"),
    "F775W_KRON_ei": ("nJy", "Uncertainty of source flux within aperture R_KRON, measured from the ERR extension"),
    "F775W_KRON_S_ei": ("nJy", "Uncertainty of source flux within aperture R_KRON_S, measured from the ERR extension"),
    "F814W_KRON_ei": ("nJy", "Uncertainty of source flux within aperture R_KRON, measured from the ERR extension"),
    "F814W_KRON_S_ei": ("nJy", "Uncertainty of source flux within aperture R_KRON_S, measured from the ERR extension"),
    "F070W_KRON_e": ("nJy", "NMAD uncertainty of source flux within aperture R_KRON, measured from a series of random apertures"),
    "F070W_KRON_S_e": ("nJy", "NMAD uncertainty of source flux within aperture R_KRON_S, measured from a series of random apertures"),
    "F090W_KRON_e": ("nJy", "NMAD uncertainty of source flux within aperture R_KRON, measured from a series of random apertures"),
    "F090W_KRON_S_e": ("nJy", "NMAD uncertainty of source flux within aperture R_KRON_S, measured from a series of random apertures"),
    "F115W_KRON_e": ("nJy", "NMAD uncertainty of source flux within aperture R_KRON, measured from a series of random apertures"),
    "F115W_KRON_S_e": ("nJy", "NMAD uncertainty of source flux within aperture R_KRON_S, measured from a series of random apertures"),
    "F150W_KRON_e": ("nJy", "NMAD uncertainty of source flux within aperture R_KRON, measured from a series of random apertures"),
    "F150W_KRON_S_e": ("nJy", "NMAD uncertainty of source flux within aperture R_KRON_S, measured from a series of random apertures"),
    "F182M_KRON_e": ("nJy", "NMAD uncertainty of source flux within aperture R_KRON, measured from a series of random apertures"),
    "F182M_KRON_S_e": ("nJy", "NMAD uncertainty of source flux within aperture R_KRON_S, measured from a series of random apertures"),
    "F200W_KRON_e": ("nJy", "NMAD uncertainty of source flux within aperture R_KRON, measured from a series of random apertures"),
    "F200W_KRON_S_e": ("nJy", "NMAD uncertainty of source flux within aperture R_KRON_S, measured from a series of random apertures"),
    "F210M_KRON_e": ("nJy", "NMAD uncertainty of source flux within aperture R_KRON, measured from a series of random apertures"),
    "F210M_KRON_S_e": ("nJy", "NMAD uncertainty of source flux within aperture R_KRON_S, measured from a series of random apertures"),
    "F277W_KRON_e": ("nJy", "NMAD uncertainty of source flux within aperture R_KRON, measured from a series of random apertures"),
    "F277W_KRON_S_e": ("nJy", "NMAD uncertainty of source flux within aperture R_KRON_S, measured from a series of random apertures"),
    "F335M_KRON_e": ("nJy", "NMAD uncertainty of source flux within aperture R_KRON, measured from a series of random apertures"),
    "F335M_KRON_S_e": ("nJy", "NMAD uncertainty of source flux within aperture R_KRON_S, measured from a series of random apertures"),
    "F356W_KRON_e": ("nJy", "NMAD uncertainty of source flux within aperture R_KRON, measured from a series of random apertures"),
    "F356W_KRON_S_e": ("nJy", "NMAD uncertainty of source flux within aperture R_KRON_S, measured from a series of random apertures"),
    "F410M_KRON_e": ("nJy", "NMAD uncertainty of source flux within aperture R_KRON, measured from a series of random apertures"),
    "F410M_KRON_S_e": ("nJy", "NMAD uncertainty of source flux within aperture R_KRON_S, measured from a series of random apertures"),
    "F430M_KRON_e": ("nJy", "NMAD uncertainty of source flux within aperture R_KRON, measured from a series of random apertures"),
    "F430M_KRON_S_e": ("nJy", "NMAD uncertainty of source flux within aperture R_KRON_S, measured from a series of random apertures"),
    "F444W_KRON_e": ("nJy", "NMAD uncertainty of source flux within aperture R_KRON, measured from a series of random apertures"),
    "F444W_KRON_S_e": ("nJy", "NMAD uncertainty of source flux within aperture R_KRON_S, measured from a series of random apertures"),
    "F460M_KRON_e": ("nJy", "NMAD uncertainty of source flux within aperture R_KRON, measured from a series of random apertures"),
    "F460M_KRON_S_e": ("nJy", "NMAD uncertainty of source flux within aperture R_KRON_S, measured from a series of random apertures"),
    "F480M_KRON_e": ("nJy", "NMAD uncertainty of source flux within aperture R_KRON, measured from a series of random apertures"),
    "F480M_KRON_S_e": ("nJy", "NMAD uncertainty of source flux within aperture R_KRON_S, measured from a series of random apertures"),
    "F435W_KRON_e": ("nJy", "NMAD uncertainty of source flux within aperture R_KRON, measured from a series of random apertures"),
    "F435W_KRON_S_e": ("nJy", "NMAD uncertainty of source flux within aperture R_KRON_S, measured from a series of random apertures"),
    "F606W_KRON_e": ("nJy", "NMAD uncertainty of source flux within aperture R_KRON, measured from a series of random apertures"),
    "F606W_KRON_S_e": ("nJy", "NMAD uncertainty of source flux within aperture R_KRON_S, measured from a series of random apertures"),
    "F775W_KRON_e": ("nJy", "NMAD uncertainty of source flux within aperture R_KRON, measured from a series of random apertures"),
    "F775W_KRON_S_e": ("nJy", "NMAD uncertainty of source flux within aperture R_KRON_S, measured from a series of random apertures"),
    "F814W_KRON_e": ("nJy", "NMAD uncertainty of source flux within aperture R_KRON, measured from a series of random apertures"),
    "F814W_KRON_S_e": ("nJy", "NMAD uncertainty of source flux within aperture R_KRON_S, measured from a series of random apertures"),
    "F850LP_KRON_e": ("nJy", "NMAD uncertainty of source flux within aperture R_KRON, measured from a series of random apertures"),
    "F850LP_KRON_S_e": ("nJy", "NMAD uncertainty of source flux within aperture R_KRON_S, measured from a series of random apertures"),
    "F105W_KRON_e": ("nJy", "NMAD uncertainty of source flux within aperture R_KRON, measured from a series of random apertures"),
    "F105W_KRON_S_e": ("nJy", "NMAD uncertainty of source flux within aperture R_KRON_S, measured from a series of random apertures"),
    "F125W_KRON_e": ("nJy", "NMAD uncertainty of source flux within aperture R_KRON, measured from a series of random apertures"),
    "F125W_KRON_S_e": ("nJy", "NMAD uncertainty of source flux within aperture R_KRON_S, measured from a series of random apertures"),
    "F140W_KRON_e": ("nJy", "NMAD uncertainty of source flux within aperture R_KRON, measured from a series of random apertures"),
    "F140W_KRON_S_e": ("nJy", "NMAD uncertainty of source flux within aperture R_KRON_S, measured from a series of random apertures"),
    "F160W_KRON_e": ("nJy", "NMAD uncertainty of source flux within aperture R_KRON, measured from a series of random apertures"),
    "F160W_KRON_S_e": ("nJy", "NMAD uncertainty of source flux within aperture R_KRON_S, measured from a series of random apertures"),
},
11: ({
    "z_spec": ("", ""),
    "z_a": ("", ""),
    "z_ml": ("", ""),
    "chi_a": ("", ""),
    "l68": ("", ""),
    "u68": ("", ""),
    "l95": ("", ""),
    "u95": ("", ""),
    "l99": ("", ""),
    "u99": ("", ""),
    "nfilt": ("", ""),
    "z_peak": ("", ""),
    "chi_peak": ("", ""),
    "z025": ("", ""),
    "z160": ("", ""),
    "z500": ("", ""),
    "z840": ("", ""),
    "z975": ("", ""),
    "Prob_gt_5": ("", ""),
    "Prob_gt_6": ("", ""),
    "Prob_gt_7": ("", ""),
    "Prob_gt_8": ("", ""),
    "Prob_gt_9": ("", ""),
    "chisq_z_lt_7": ("", ""),
    "z_chisq_z_lt_7": ("", ""),
    "chisq_z_lt_6": ("", ""),
    "z_chisq_z_lt_6": ("", ""),
    "chisq_z_lt_5": ("", ""),
    "z_chisq_z_lt_5": ("", ""),
    "chisq_z_lt_4": ("", ""),
    "z_chisq_z_lt_4": ("", ""),
}, "pz_"),
12: ({
    "z_spec": ("", ""),
    "z_a": ("", ""),
    "z_ml": ("", ""),
    "chi_a": ("", ""),
    "l68": ("", ""),
    "u68": ("", ""),
    "l95": ("", ""),
    "u95": ("", ""),
    "l99": ("", ""),
    "u99": ("", ""),
    "nfilt": ("", ""),
    "z_peak": ("", ""),
    "chi_peak": ("", ""),
    "z025": ("", ""),
    "z160": ("", ""),
    "z500": ("", ""),
    "z840": ("", ""),
    "z975": ("", ""),
    "Prob_gt_5": ("", ""),
    "Prob_gt_6": ("", ""),
    "Prob_gt_7": ("", ""),
    "Prob_gt_8": ("", ""),
    "Prob_gt_9": ("", ""),
    "chisq_z_lt_7": ("", ""),
    "z_chisq_z_lt_7": ("", ""),
    "chisq_z_lt_6": ("", ""),
    "z_chisq_z_lt_6": ("", ""),
    "chisq_z_lt_5": ("", ""),
    "z_chisq_z_lt_5": ("", ""),
    "chisq_z_lt_4": ("", ""),
    "z_chisq_z_lt_4": ("", ""),
}, "pz_kron_"),
}

tables = []

for hdu, columns in columns_hdu.items():
    if hdu >= 11:
        columns, prefix = columns
    else:
        prefix = ""
    tab = apTab.Table.read(filename, hdu=hdu)[list(columns.keys())]
    tab_meta = tab.meta
    for colname, (unit, desc) in columns.items():
        tab[colname].unit = u.Unit(unit)
        tab[colname].description = desc
    tab.meta = {tab_meta.pop("EXTNAME"): tab_meta}
    if prefix:
        tab.rename_columns(tab.colnames, [f"{prefix}{name}" for name in tab.colnames])
    tables.append(tab)

tab_ap = apTab.hstack(tables)

coords = [
    SpherePoint(ra, dec, degrees) for ra, dec in zip(tab_ap["RA"], tab_ap["DEC"])
]
within = np.array([tractInfo.contains(coord) for coord in coords])
if np.sum(within) != len(within):
    tab_ap = tab_ap[within]
    coords = [coord for coord, in_tract in zip(coords, within) if in_tract]
patches = np.array(
    [tractInfo.findPatch(coord).getSequentialIndex() for coord in coords],
    dtype=np.int16,
)
tab_ap["patch"] = patches
tab_ap["patch"].description = f"{skymap} patch index"

tab_arrow = astropy_to_arrow(tab_ap)
row_group_size = compute_row_group_size(tab_arrow.schema)

pq.write_table(tab_arrow, f"{name_tab}.parq", row_group_size=row_group_size)
