import astropy.table as apTab
import astropy.units as u
from lsst.daf.butler.formatters.parquet import astropy_to_arrow, compute_row_group_size
import pyarrow.parquet as pq

# from https://datalab.noirlab.edu/query.php?name=des_dr1.y3_gold
# downloaded in four chunks because the whole query didn't work
# ra: 52.14077598745257, 54.03427611473381
# dec: -28.35063896360024, -26.684313552983653

name_tab = "des_y3gold_lsst_cells_v1_5063"

tab_ap = apTab.Table.read(f"{name_tab}.csv")

columns = (
    ("a_fiducial_g", "SED-independent interstellar extinction based on the E(B - V) reddening maps from Schlegel, Finkbeiner & Davis (1998) in band GRIZY [magnitudes]"),
    ("a_fiducial_i", "SED-independent interstellar extinction based on the E(B - V) reddening maps from Schlegel, Finkbeiner & Davis (1998) in band GRIZY [magnitudes]"),
    ("a_fiducial_r", "SED-independent interstellar extinction based on the E(B - V) reddening maps from Schlegel, Finkbeiner & Davis (1998) in band GRIZY [magnitudes]"),
    ("a_fiducial_y", "SED-independent interstellar extinction based on the E(B - V) reddening maps from Schlegel, Finkbeiner & Davis (1998) in band GRIZY [magnitudes]"),
    ("a_fiducial_z", "SED-independent interstellar extinction based on the E(B - V) reddening maps from Schlegel, Finkbeiner & Davis (1998) in band GRIZY [magnitudes]"),
    ("a_image", "Detection image based basic shape parameter; A = semimajor-axis [pixels]"),
    ("a_sed_lenz17_g", "SED-dependent interstellar extinction based on the E(B - V) reddening maps from Lenz et al. (2017) [magnitudes]"),
    ("a_sed_lenz17_i", "SED-dependent interstellar extinction based on the E(B - V) reddening maps from Lenz et al. (2017) [magnitudes]"),
    ("a_sed_lenz17_r", "SED-dependent interstellar extinction based on the E(B - V) reddening maps from Lenz et al. (2017) [magnitudes]"),
    ("a_sed_lenz17_y", "SED-dependent interstellar extinction based on the E(B - V) reddening maps from Lenz et al. (2017) [magnitudes]"),
    ("a_sed_lenz17_z", "SED-dependent interstellar extinction based on the E(B - V) reddening maps from Lenz et al. (2017) [magnitudes]"),
    ("a_sed_planck13_g", "SED-dependent interstellar extinction based on the E(B - V) reddening maps from Planck Collaboration (2014) [magnitudes]"),
    ("a_sed_planck13_i", "SED-dependent interstellar extinction based on the E(B - V) reddening maps from Planck Collaboration (2014) [magnitudes]"),
    ("a_sed_planck13_r", "SED-dependent interstellar extinction based on the E(B - V) reddening maps from Planck Collaboration (2014) [magnitudes]"),
    ("a_sed_planck13_y", "SED-dependent interstellar extinction based on the E(B - V) reddening maps from Planck Collaboration (2014) [magnitudes]"),
    ("a_sed_planck13_z", "SED-dependent interstellar extinction based on the E(B - V) reddening maps from Planck Collaboration (2014) [magnitudes]"),
    ("a_sed_sfd98_g", "SED-dependent interstellar extinction based on the E(B - V) reddening maps from Schlegel, Finkbeiner & Davis (1998) ; used in the CORRECTED columns; current recommendation [magnitudes]"),
    ("a_sed_sfd98_i", "SED-dependent interstellar extinction based on the E(B - V) reddening maps from Schlegel, Finkbeiner & Davis (1998) ; used in the CORRECTED columns; current recommendation [magnitudes]"),
    ("a_sed_sfd98_r", "SED-dependent interstellar extinction based on the E(B - V) reddening maps from Schlegel, Finkbeiner & Davis (1998) ; used in the CORRECTED columns; current recommendation [magnitudes]"),
    ("a_sed_sfd98_y", "SED-dependent interstellar extinction based on the E(B - V) reddening maps from Schlegel, Finkbeiner & Davis (1998) ; used in the CORRECTED columns; current recommendation [magnitudes]"),
    ("a_sed_sfd98_z", "SED-dependent interstellar extinction based on the E(B - V) reddening maps from Schlegel, Finkbeiner & Davis (1998) ; used in the CORRECTED columns; current recommendation [magnitudes]"),
    ("alphawin_j2000", "Right Ascension (J2000.0) of the object using a Gaussian window with a FWHM corresponding to the disk containing 50% of the flux. [degrees]"),
    ("b", "Latitude in Galactic coordinates [degrees]"),
    ("b_image", "Detection image based basic shape parameter; B = semiminor-axis [pixels]"),
    ("bpz_template_id_mof", "Template identification from the BPZ code"),
    ("bpz_template_id_sof", "Template identification from the BPZ code"),
    ("bpz_zmc_mof", "MonteCarlo instance from the redshift distribution computed from BPZ"),
    ("bpz_zmc_sof", "MonteCarlo instance from the redshift distribution computed from BPZ"),
    ("bpz_zmean_mof", "Mean of the redshift distribution computed from BPZ"),
    ("bpz_zmean_sof", "Mean of the redshift distribution computed from BPZ"),
    ("bpz_zmode_mof", "Mode of the redshift distribution computed from BPZ"),
    ("bpz_zmode_sof", "Mode of the redshift distribution computed from BPZ"),
    ("bpz_zsigma68_mof", "Width of the 68% quantile"),
    ("bpz_zsigma68_sof", "Width of the 68% quantile"),
    ("bpz_zsigma_mof", "Width of the redshift distribution computed from BPZ"),
    ("bpz_zsigma_sof", "Width of the redshift distribution computed from BPZ"),
    ("class_star_g", "Morphology based star-galaxy classifier from SExtractor. Values between 0 (galaxies) and 1 (stars)."),
    ("class_star_i", "Morphology based star-galaxy classifier from SExtractor. Values between 0 (galaxies) and 1 (stars)."),
    ("class_star_r", "Morphology based star-galaxy classifier from SExtractor. Values between 0 (galaxies) and 1 (stars)."),
    ("class_star_y", "Morphology based star-galaxy classifier from SExtractor. Values between 0 (galaxies) and 1 (stars)."),
    ("class_star_z", "Morphology based star-galaxy classifier from SExtractor. Values between 0 (galaxies) and 1 (stars)."),
    ("coadd_object_id", "Unique identifier for the coadded objects"),
    ("dec", "Declination (J2000.0) with quantized precision for indexing (DELTAWIN_J2000 has full precision but not indexed) [degrees]"),
    ("delta_mag_chrom_g", "Coadd object chromatic correction using an appropriate spectral template for the object. See section 4.3 of Sevilla-Noarbe et al. (2021)"),
    ("delta_mag_chrom_i", "Coadd object chromatic correction using an appropriate spectral template for the object. See section 4.3 of Sevilla-Noarbe et al. (2021)"),
    ("delta_mag_chrom_r", "Coadd object chromatic correction using an appropriate spectral template for the object. See section 4.3 of Sevilla-Noarbe et al. (2021)"),
    ("delta_mag_chrom_y", "Coadd object chromatic correction using an appropriate spectral template for the object. See section 4.3 of Sevilla-Noarbe et al. (2021)"),
    ("delta_mag_chrom_z", "Coadd object chromatic correction using an appropriate spectral template for the object. See section 4.3 of Sevilla-Noarbe et al. (2021)"),
    ("delta_mag_y4_g", "Updates to photometry using Year 4 imaging. See section 4.3 of Sevilla-Noarbe et al. (2021)."),
    ("delta_mag_y4_i", "Updates to photometry using Year 4 imaging. See section 4.3 of Sevilla-Noarbe et al. (2021)."),
    ("delta_mag_y4_r", "Updates to photometry using Year 4 imaging. See section 4.3 of Sevilla-Noarbe et al. (2021)."),
    ("delta_mag_y4_y", "Updates to photometry using Year 4 imaging. See section 4.3 of Sevilla-Noarbe et al. (2021)."),
    ("delta_mag_y4_z", "Updates to photometry using Year 4 imaging. See section 4.3 of Sevilla-Noarbe et al. (2021)."),
    ("deltawin_j2000", "Declination (J2000.0) of the object using a Gaussian window with a FWHM corresponding to the disk containing 50% of the flux. [degrees]"),
    ("dnf_zmc_mof", "Nearest neighbor redshift from the reference set produced by the DNF photo-z estimator. Appropriate for building ensemble redshift distributions"),
    ("dnf_zmc_sof", "Nearest neighbor redshift from the reference set produced by the DNF photo-z estimator. Appropriate for building ensemble redshift distributions"),
    ("dnf_zmean_mof", "Best redshift estimate from the DNF photo-z algorithm."),
    ("dnf_zmean_sof", "Best redshift estimate from the DNF photo-z algorithm."),
    ("dnf_zsigma_mof", "Error estimate in redshift from the DNF photo-z algorithm."),
    ("dnf_zsigma_sof", "Error estimate in redshift from the DNF photo-z algorithm."),
    ("ebv_lenz17", "E(B-V) reddening coefficient from Lenz et al. (2017)"),
    ("ebv_planck13", "E(B-V) reddening coefficient from Planck Collaboration (2014)"),
    ("ebv_sfd98", "E(B-V) reddening coefficient from Schlegel, Finkbeiner & Davis (1998)"),
    ("elat", "Ecliptic Latitude"),
    ("elon", "Ecliptic Longitude"),
    ("erra_image", "Uncertainty in major axis size, from isophotal model [pixel]"),
    ("errb_image", "Uncertainty in minor axis size, from isophotal model [pixel]"),
    ("errtheta_image", "Uncertainty in source position, from isophotal model [degrees]"),
    ("extended_class_coadd", "Star/galaxy separation using SExtractor photometry and SPREAD_MODEL, SPREAD_MODEL_ERR in the i band. 0: high confidence stars; 1: candidate stars; 2: mostly galaxies; 3: high confidence galaxies; -9: No data"),
    ("extended_class_mash_mof", "Star/galaxy separation using MOF/SOF photometry in the i band, and WAVG and finally coadd quantities in case of missing values. 0: high confidence stars; 1: candidate stars; 2: mostly galaxies; 3: high confidence galaxies; -9: No data"),
    ("extended_class_mash_sof", "Star/galaxy separation using MOF/SOF photometry in the i band, and WAVG and finally coadd quantities in case of missing values. 0: high confidence stars; 1: candidate stars; 2: mostly galaxies; 3: high confidence galaxies; -9: No data"),
    ("extended_class_mof", "Star/galaxy separation using MOF/SOF photometry and T_SIZE in the i band. 0: high confidence stars; 1: candidate stars; 2: mostly galaxies; 3: high confidence galaxies; -9: No data"),
    ("extended_class_sof", "Star/galaxy separation using MOF/SOF photometry and T_SIZE in the i band. 0: high confidence stars; 1: candidate stars; 2: mostly galaxies; 3: high confidence galaxies; -9: No data"),
    ("extended_class_wavg", "Star/galaxy separation using WAVG photometry and SPREAD_MODEL, SPREAD_MODEL_ERR in the i band. 0: high confidence stars; 1: candidate stars; 2: mostly galaxies; 3: high confidence galaxies; -9: No data"),
    ("flags_badregions", "Flag describing whether the object is contained in a region with potentially problematic processing. See Sevilla-Noarbe et al. (2021) for description."),
    ("flags_footprint", "Flag describing whether the object is contained in the fiducial footprint of the survey. See Sevilla-Noarbe et al. (2021) for description."),
    ("flags_foreground", "Flag describing whether the object is contained in a region with a foreground astrophysical object. See Sevilla-Noarbe et al. (2021) for description."),
    ("flags_gold", "Flag describing object anomalies. See Sevilla-Noarbe et al. (2021) for description."),
    ("flux_aper_8_g", "Flux measurement in a circular aperture of 22.22 pixels (5.8437 arcsecs) diameter; MAG=30-2.5*log10(FLUX) [ADU]"),
    ("flux_aper_8_i", "Flux measurement in a circular aperture of 22.22 pixels (5.8437 arcsecs) diameter; MAG=30-2.5*log10(FLUX) [ADU]"),
    ("flux_aper_8_r", "Flux measurement in a circular aperture of 22.22 pixels (5.8437 arcsecs) diameter; MAG=30-2.5*log10(FLUX) [ADU]"),
    ("flux_aper_8_y", "Flux measurement in a circular aperture of 22.22 pixels (5.8437 arcsecs) diameter; MAG=30-2.5*log10(FLUX) [ADU]"),
    ("flux_aper_8_z", "Flux measurement in a circular aperture of 22.22 pixels (5.8437 arcsecs) diameter; MAG=30-2.5*log10(FLUX) [ADU]"),
    ("flux_auto_g", "Flux measurement in an elliptical aperture, shaped by the second moments of the object and scaled by the Kron radius; MAG=30-2.5*log10(FLUX) [ADU]"),
    ("flux_auto_i", "Flux measurement in an elliptical aperture, shaped by the second moments of the object and scaled by the Kron radius; MAG=30-2.5*log10(FLUX) [ADU]"),
    ("flux_auto_r", "Flux measurement in an elliptical aperture, shaped by the second moments of the object and scaled by the Kron radius; MAG=30-2.5*log10(FLUX) [ADU]"),
    ("flux_auto_y", "Flux measurement in an elliptical aperture, shaped by the second moments of the object and scaled by the Kron radius; MAG=30-2.5*log10(FLUX) [ADU]"),
    ("flux_auto_z", "Flux measurement in an elliptical aperture, shaped by the second moments of the object and scaled by the Kron radius; MAG=30-2.5*log10(FLUX) [ADU]"),
    ("flux_detmodel_g", "Flux measurement, for a bulge + disk model fit on the detection image [ADU]"),
    ("flux_detmodel_i", "Flux measurement, for a bulge + disk model fit on the detection image [ADU]"),
    ("flux_detmodel_r", "Flux measurement, for a bulge + disk model fit on the detection image [ADU]"),
    ("flux_detmodel_y", "Flux measurement, for a bulge + disk model fit on the detection image [ADU]"),
    ("flux_detmodel_z", "Flux measurement, for a bulge + disk model fit on the detection image [ADU]"),
    ("flux_radius_g", "Half-light radius for the object, from elliptical growth-curve, modeled in 2 dimensions [pixel]"),
    ("flux_radius_i", "Half-light radius for the object, from elliptical growth-curve, modeled in 2 dimensions [pixel]"),
    ("flux_radius_r", "Half-light radius for the object, from elliptical growth-curve, modeled in 2 dimensions [pixel]"),
    ("flux_radius_y", "Half-light radius for the object, from elliptical growth-curve, modeled in 2 dimensions [pixel]"),
    ("flux_radius_z", "Half-light radius for the object, from elliptical growth-curve, modeled in 2 dimensions [pixel]"),
    ("fluxerr_aper_8_g", "RMS error estimate of FLUX_APER_8 [ADU]"),
    ("fluxerr_aper_8_i", "RMS error estimate of FLUX_APER_8 [ADU]"),
    ("fluxerr_aper_8_r", "RMS error estimate of FLUX_APER_8 [ADU]"),
    ("fluxerr_aper_8_y", "RMS error estimate of FLUX_APER_8 [ADU]"),
    ("fluxerr_aper_8_z", "RMS error estimate of FLUX_APER_8 [ADU]"),
    ("fluxerr_auto_g", "RMS error estimate of FLUX_AUTO [ADU]"),
    ("fluxerr_auto_i", "RMS error estimate of FLUX_AUTO [ADU]"),
    ("fluxerr_auto_r", "RMS error estimate of FLUX_AUTO [ADU]"),
    ("fluxerr_auto_y", "RMS error estimate of FLUX_AUTO [ADU]"),
    ("fluxerr_auto_z", "RMS error estimate of FLUX_AUTO [ADU]"),
    ("fluxerr_detmodel_g", "RMS error estimate of FLUX_DETMODEL measurement [ADU]"),
    ("fluxerr_detmodel_i", "RMS error estimate of FLUX_DETMODEL measurement [ADU]"),
    ("fluxerr_detmodel_r", "RMS error estimate of FLUX_DETMODEL measurement [ADU]"),
    ("fluxerr_detmodel_y", "RMS error estimate of FLUX_DETMODEL measurement [ADU]"),
    ("fluxerr_detmodel_z", "RMS error estimate of FLUX_DETMODEL measurement [ADU]"),
    ("frac_det_griz", "Fractional area of Healpix pixel covered simultaneously by griz bands"),
    ("frac_det_grizy", "Fractional area of Healpix pixel covered simultaneously by grizY bands"),
    ("hpix_16384", "Healpix index for NSIDE = 16384 in NEST schema for the object"),
    ("hpix_4096", "Healpix index for NSIDE = 4096 in NEST schema for the object"),
    ("htm9", "Ninth level (~10 arcmin resolution) Hierarchical Triangular Mesh index (Szalay et al. 2007)"),
    ("imaflags_iso_g", "Flag identifying sources with missing/flagged pixels, considering all single epoch images"),
    ("imaflags_iso_i", "Flag identifying sources with missing/flagged pixels, considering all single epoch images"),
    ("imaflags_iso_r", "Flag identifying sources with missing/flagged pixels, considering all single epoch images"),
    ("imaflags_iso_y", "Flag identifying sources with missing/flagged pixels, considering all single epoch images"),
    ("imaflags_iso_z", "Flag identifying sources with missing/flagged pixels, considering all single epoch images"),
    ("kron_radius", "Detection image luminosity weighted radius for the object, encompassing approximately 90% of the total flux"),
    ("l", "Longitude in Galactic coordinates [degrees]"),
    ("mag_aper_8_g", "Magnitude measured in a circular aperture of 22.22 pixels (5.8437 arcsecs) diameter [magnitudes]"),
    ("mag_aper_8_i", "Magnitude measured in a circular aperture of 22.22 pixels (5.8437 arcsecs) diameter [magnitudes]"),
    ("mag_aper_8_r", "Magnitude measured in a circular aperture of 22.22 pixels (5.8437 arcsecs) diameter [magnitudes]"),
    ("mag_aper_8_y", "Magnitude measured in a circular aperture of 22.22 pixels (5.8437 arcsecs) diameter [magnitudes]"),
    ("mag_aper_8_z", "Magnitude measured in a circular aperture of 22.22 pixels (5.8437 arcsecs) diameter [magnitudes]"),
    ("mag_auto_g", "Magnitude measurement in an elliptical aperture, shaped by the second moments of the object and scaled by the Kron radius [magnitudes]"),
    ("mag_auto_i", "Magnitude measurement in an elliptical aperture, shaped by the second moments of the object and scaled by the Kron radius [magnitudes]"),
    ("mag_auto_r", "Magnitude measurement in an elliptical aperture, shaped by the second moments of the object and scaled by the Kron radius [magnitudes]"),
    ("mag_auto_y", "Magnitude measurement in an elliptical aperture, shaped by the second moments of the object and scaled by the Kron radius [magnitudes]"),
    ("mag_auto_z", "Magnitude measurement in an elliptical aperture, shaped by the second moments of the object and scaled by the Kron radius [magnitudes]"),
    ("mag_detmodel_g", "Magnitude measurement, for a bulge + disk model fit on the detection image [magnitudes]"),
    ("mag_detmodel_i", "Magnitude measurement, for a bulge + disk model fit on the detection image [magnitudes]"),
    ("mag_detmodel_r", "Magnitude measurement, for a bulge + disk model fit on the detection image [magnitudes]"),
    ("mag_detmodel_y", "Magnitude measurement, for a bulge + disk model fit on the detection image [magnitudes]"),
    ("mag_detmodel_z", "Magnitude measurement, for a bulge + disk model fit on the detection image [magnitudes]"),
    ("mag_psf_g", "Magnitude measured using the coadd PSF (use caution as this PSF varies discontinuously across footprint) [magnitudes]"),
    ("mag_psf_i", "Magnitude measured using the coadd PSF (use caution as this PSF varies discontinuously across footprint) [magnitudes]"),
    ("mag_psf_r", "Magnitude measured using the coadd PSF (use caution as this PSF varies discontinuously across footprint) [magnitudes]"),
    ("mag_psf_y", "Magnitude measured using the coadd PSF (use caution as this PSF varies discontinuously across footprint) [magnitudes]"),
    ("mag_psf_z", "Magnitude measured using the coadd PSF (use caution as this PSF varies discontinuously across footprint) [magnitudes]"),
    ("magerr_aper_8_g", "Error in MAG_APER_8, scaled from FLUXERR_APER_8 [magnitudes]"),
    ("magerr_aper_8_i", "Error in MAG_APER_8, scaled from FLUXERR_APER_8 [magnitudes]"),
    ("magerr_aper_8_r", "Error in MAG_APER_8, scaled from FLUXERR_APER_8 [magnitudes]"),
    ("magerr_aper_8_y", "Error in MAG_APER_8, scaled from FLUXERR_APER_8 [magnitudes]"),
    ("magerr_aper_8_z", "Error in MAG_APER_8, scaled from FLUXERR_APER_8 [magnitudes]"),
    ("magerr_auto_g", "Error in MAG_AUTO, scaled from FLUXERR_AUTO [magnitudes]"),
    ("magerr_auto_i", "Error in MAG_AUTO, scaled from FLUXERR_AUTO [magnitudes]"),
    ("magerr_auto_r", "Error in MAG_AUTO, scaled from FLUXERR_AUTO [magnitudes]"),
    ("magerr_auto_y", "Error in MAG_AUTO, scaled from FLUXERR_AUTO [magnitudes]"),
    ("magerr_auto_z", "Error in MAG_AUTO, scaled from FLUXERR_AUTO [magnitudes]"),
    ("magerr_detmodel_g", "Error in MAG_DETMODEL, scaled from FLUXERR_DETMODEL [magnitudes]"),
    ("magerr_detmodel_i", "Error in MAG_DETMODEL, scaled from FLUXERR_DETMODEL [magnitudes]"),
    ("magerr_detmodel_r", "Error in MAG_DETMODEL, scaled from FLUXERR_DETMODEL [magnitudes]"),
    ("magerr_detmodel_y", "Error in MAG_DETMODEL, scaled from FLUXERR_DETMODEL [magnitudes]"),
    ("magerr_detmodel_z", "Error in MAG_DETMODEL, scaled from FLUXERR_DETMODEL [magnitudes]"),
    ("magerr_psf_g", "Error in MAG_PSF, scaled from MAG_PSF [magnitudes]"),
    ("magerr_psf_i", "Error in MAG_PSF, scaled from MAG_PSF [magnitudes]"),
    ("magerr_psf_r", "Error in MAG_PSF, scaled from MAG_PSF [magnitudes]"),
    ("magerr_psf_y", "Error in MAG_PSF, scaled from MAG_PSF [magnitudes]"),
    ("magerr_psf_z", "Error in MAG_PSF, scaled from MAG_PSF [magnitudes]"),
    ("mof_cm_chi2per", "Chi2 per degree of freedom of the composite model fit"),
    ("mof_cm_dof", "Number of the degrees of freedom for the composite model fit"),
    ("mof_cm_flux_cov_g_g", "Diagonal covariance of the MOF CM flux in the g band"),
    ("mof_cm_flux_cov_i_i", "Diagonal covariance of the MOF CM flux in the i band"),
    ("mof_cm_flux_cov_r_r", "Diagonal covariance of the MOF CM flux in the r band"),
    ("mof_cm_flux_cov_z_z", "Diagonal covariance of the MOF CM flux in the z band"),
    ("mof_cm_flux_g", "Measured MOF composite model flux [ADU]"),
    ("mof_cm_flux_i", "Measured MOF composite model flux [ADU]"),
    ("mof_cm_flux_r", "Measured MOF composite model flux [ADU]"),
    ("mof_cm_flux_s2n_g", "MOF composite model flux signal to noise ratio"),
    ("mof_cm_flux_s2n_i", "MOF composite model flux signal to noise ratio"),
    ("mof_cm_flux_s2n_r", "MOF composite model flux signal to noise ratio"),
    ("mof_cm_flux_s2n_z", "MOF composite model flux signal to noise ratio"),
    ("mof_cm_flux_z", "Measured MOF composite model flux [ADU]"),
    ("mof_cm_fracdev", "MOF composite model fraction of de Vaucouleurs flux: cm = fracdev * devaucouleurs + (1-fracdev) * exponential"),
    ("mof_cm_fracdev_err", "Error in FRACDEV"),
    ("mof_cm_fracdev_noclip", "Value of FRACDEV if not clipped to [0,1] range"),
    ("mof_cm_g_1", "MOF based shape component 1 (reduced version of e1)"),
    ("mof_cm_g_2", "MOF based shape component 2 (reduced version of e2)"),
    ("mof_cm_g_cov_1_1", "MOF based shape covariance component 1-1"),
    ("mof_cm_g_cov_1_2", "MOF based shape covariance component 1-2"),
    ("mof_cm_g_cov_2_1", "MOF based shape covariance component 2-1"),
    ("mof_cm_g_cov_2_2", "MOF based shape covariance component 2-2"),
    ("mof_cm_logsb_g", "Logarithm of the MOF based surface brightness"),
    ("mof_cm_logsb_i", "Logarithm of the MOF based surface brightness"),
    ("mof_cm_logsb_r", "Logarithm of the MOF based surface brightness"),
    ("mof_cm_logsb_z", "Logarithm of the MOF based surface brightness"),
    ("mof_cm_mag_corrected_g", "MOF corrected magnitude = MOF_CM_MAG + DELTA_MAG_Y4 + DELTA_MAG_CHROM + A_SED_SFD98"),
    ("mof_cm_mag_corrected_i", "MOF corrected magnitude = MOF_CM_MAG + DELTA_MAG_Y4 + DELTA_MAG_CHROM + A_SED_SFD98"),
    ("mof_cm_mag_corrected_r", "MOF corrected magnitude = MOF_CM_MAG + DELTA_MAG_Y4 + DELTA_MAG_CHROM + A_SED_SFD98"),
    ("mof_cm_mag_corrected_z", "MOF corrected magnitude = MOF_CM_MAG + DELTA_MAG_Y4 + DELTA_MAG_CHROM + A_SED_SFD98"),
    ("mof_cm_mag_err_g", "Uncertainty in MOF magnitude"),
    ("mof_cm_mag_err_i", "Uncertainty in MOF magnitude"),
    ("mof_cm_mag_err_r", "Uncertainty in MOF magnitude"),
    ("mof_cm_mag_err_z", "Uncertainty in MOF magnitude"),
    ("mof_cm_mag_g", "Magnitude from MOF_CM_FLUX. MAG = 30-2.5*log10(FLUX)"),
    ("mof_cm_mag_i", "Magnitude from MOF_CM_FLUX. MAG = 30-2.5*log10(FLUX)"),
    ("mof_cm_mag_r", "Magnitude from MOF_CM_FLUX. MAG = 30-2.5*log10(FLUX)"),
    ("mof_cm_mag_z", "Magnitude from MOF_CM_FLUX. MAG = 30-2.5*log10(FLUX)"),
    ("mof_cm_t", "Size squared of the object: T=+ [arcsec**2]"),
    ("mof_cm_t_err", "Error in size squared [arcsec**2]"),
    ("mof_cm_tdbyte", "Ratio of sizes Tdev/Texp"),
    ("mof_flags", "Overall image processing flags. Can contain NULLs for objects with unfinished processing for MOF"),
    ("mof_psf_flux_err_g", "Uncertainty in measured MOF PSF flux [ADU]"),
    ("mof_psf_flux_err_i", "Uncertainty in measured MOF PSF flux [ADU]"),
    ("mof_psf_flux_err_r", "Uncertainty in measured MOF PSF flux [ADU]"),
    ("mof_psf_flux_err_z", "Uncertainty in measured MOF PSF flux [ADU]"),
    ("mof_psf_flux_g", "Measured MOF PSF flux [ADU]"),
    ("mof_psf_flux_i", "Measured MOF PSF flux [ADU]"),
    ("mof_psf_flux_r", "Measured MOF PSF flux [ADU]"),
    ("mof_psf_flux_s2n_g", "MOF PSF flux signal to noise ratio"),
    ("mof_psf_flux_s2n_i", "MOF PSF flux signal to noise ratio"),
    ("mof_psf_flux_s2n_r", "MOF PSF flux signal to noise ratio"),
    ("mof_psf_flux_s2n_z", "MOF PSF flux signal to noise ratio"),
    ("mof_psf_flux_z", "Measured MOF PSF flux [ADU]"),
    ("mof_psf_mag_err_g", "Uncertainty in MOF PSF magnitude"),
    ("mof_psf_mag_err_i", "Uncertainty in MOF PSF magnitude"),
    ("mof_psf_mag_err_r", "Uncertainty in MOF PSF magnitude"),
    ("mof_psf_mag_err_z", "Uncertainty in MOF PSF magnitude"),
    ("mof_psf_mag_g", "Magnitude from MOF_PSF_FLUX. MAG = 30-2.5*log10(FLUX)"),
    ("mof_psf_mag_i", "Magnitude from MOF_PSF_FLUX. MAG = 30-2.5*log10(FLUX)"),
    ("mof_psf_mag_r", "Magnitude from MOF_PSF_FLUX. MAG = 30-2.5*log10(FLUX)"),
    ("mof_psf_mag_z", "Magnitude from MOF_PSF_FLUX. MAG = 30-2.5*log10(FLUX)"),
    ("mu_eff_model_g", "Effective model surface brightness above background. The surface brightness is measured at the isophote which includes half of the flux of the model, above background [mag./sq.arcsec]"),
    ("mu_eff_model_i", "Effective model surface brightness above background. The surface brightness is measured at the isophote which includes half of the flux of the model, above background [mag./sq.arcsec]"),
    ("mu_eff_model_r", "Effective model surface brightness above background. The surface brightness is measured at the isophote which includes half of the flux of the model, above background [mag./sq.arcsec]"),
    ("mu_eff_model_y", "Effective model surface brightness above background. The surface brightness is measured at the isophote which includes half of the flux of the model, above background [mag./sq.arcsec]"),
    ("mu_eff_model_z", "Effective model surface brightness above background. The surface brightness is measured at the isophote which includes half of the flux of the model, above background [mag./sq.arcsec]"),
    ("mu_max_g", "Surface brightness at the brightest pixel [mag./sq.arcsec]"),
    ("mu_max_i", "Surface brightness at the brightest pixel [mag./sq.arcsec]"),
    ("mu_max_model_g", "Maximum surface brightness using the whole area inside the isophote used for MU_EFF_MODEL [mag./sq.arcsec]"),
    ("mu_max_model_i", "Maximum surface brightness using the whole area inside the isophote used for MU_EFF_MODEL [mag./sq.arcsec]"),
    ("mu_max_model_r", "Maximum surface brightness using the whole area inside the isophote used for MU_EFF_MODEL [mag./sq.arcsec]"),
    ("mu_max_model_y", "Maximum surface brightness using the whole area inside the isophote used for MU_EFF_MODEL [mag./sq.arcsec]"),
    ("mu_max_model_z", "Maximum surface brightness using the whole area inside the isophote used for MU_EFF_MODEL [mag./sq.arcsec]"),
    ("mu_max_r", "Surface brightness at the brightest pixel [mag./sq.arcsec]"),
    ("mu_max_y", "Surface brightness at the brightest pixel [mag./sq.arcsec]"),
    ("mu_max_z", "Surface brightness at the brightest pixel [mag./sq.arcsec]"),
    ("mu_mean_model_g", "Mean surface brightness using the whole area inside the isophote used for MU_EFF_MODEL [mag./sq.arcsec]"),
    ("mu_mean_model_i", "Mean surface brightness using the whole area inside the isophote used for MU_EFF_MODEL [mag./sq.arcsec]"),
    ("mu_mean_model_r", "Mean surface brightness using the whole area inside the isophote used for MU_EFF_MODEL [mag./sq.arcsec]"),
    ("mu_mean_model_y", "Mean surface brightness using the whole area inside the isophote used for MU_EFF_MODEL [mag./sq.arcsec]"),
    ("mu_mean_model_z", "Mean surface brightness using the whole area inside the isophote used for MU_EFF_MODEL [mag./sq.arcsec]"),
    ("mu_threshold_g", "Surface brightness threshold (SExtractor parameter) [mag./sq.arcsec.]"),
    ("mu_threshold_i", "Surface brightness threshold (SExtractor parameter) [mag./sq.arcsec.]"),
    ("mu_threshold_r", "Surface brightness threshold (SExtractor parameter) [mag./sq.arcsec.]"),
    ("mu_threshold_y", "Surface brightness threshold (SExtractor parameter) [mag./sq.arcsec.]"),
    ("mu_threshold_z", "Surface brightness threshold (SExtractor parameter) [mag./sq.arcsec.]"),
    ("n_images_g", "Number of (grizY) band exposures at the object location (from the Healpix map)"),
    ("n_images_i", "Number of (grizY) band exposures at the object location (from the Healpix map)"),
    ("n_images_r", "Number of (grizY) band exposures at the object location (from the Healpix map)"),
    ("n_images_y", "Number of (grizY) band exposures at the object location (from the Healpix map)"),
    ("n_images_z", "Number of (grizY) band exposures at the object location (from the Healpix map)"),
    ("nepochs_g", "Number of epochs the source is detected in single epoch images"),
    ("nepochs_i", "Number of epochs the source is detected in single epoch images"),
    ("nepochs_r", "Number of epochs the source is detected in single epoch images"),
    ("nepochs_y", "Number of epochs the source is detected in single epoch images"),
    ("nepochs_z", "Number of epochs the source is detected in single epoch images"),
    ("niter_model_g", "Number of iterations for convergence in SExtractor model fitting"),
    ("niter_model_i", "Number of iterations for convergence in SExtractor model fitting"),
    ("niter_model_r", "Number of iterations for convergence in SExtractor model fitting"),
    ("niter_model_y", "Number of iterations for convergence in SExtractor model fitting"),
    ("niter_model_z", "Number of iterations for convergence in SExtractor model fitting"),
    ("object_number", "SExtractor unique number for a processing tile"),
    ("parent_number", "SExtractor OBJECT_NUMBER of parent object of which this object is a deblended child"),
    ("ra", "Right Ascension (J2000.0) with quantized precision for indexing (ALPHAWIN_J2000 has full precision but not indexed) [degrees]"),
    ("random_id", "Random ID in the range 0.0 => 100.0"),
    ("ring256", "Ring-scheme HEALPix (Gorski et al. 2005) index with NSIDE=256 (~14 arcmin resolution)"),
    ("sextractor_flags_g", "SExtractor 16-bit flag parameter which contains basic warnings about the source extraction process"),
    ("sextractor_flags_i", "SExtractor 16-bit flag parameter which contains basic warnings about the source extraction process"),
    ("sextractor_flags_r", "SExtractor 16-bit flag parameter which contains basic warnings about the source extraction process"),
    ("sextractor_flags_y", "SExtractor 16-bit flag parameter which contains basic warnings about the source extraction process"),
    ("sextractor_flags_z", "SExtractor 16-bit flag parameter which contains basic warnings about the source extraction process"),
    ("sof_cm_chi2per", "Chi2 per degree of freedom of the composite model fit"),
    ("sof_cm_dof", "Number of the degrees of freedom for the composite model fit"),
    ("sof_cm_flux_cov_g_g", "Diagonal covariance of the SOF CM flux in the g band"),
    ("sof_cm_flux_cov_i_i", "Diagonal covariance of the SOF CM flux in the i band"),
    ("sof_cm_flux_cov_r_r", "Diagonal covariance of the SOF CM flux in the r band"),
    ("sof_cm_flux_cov_z_z", "Diagonal covariance of the SOF CM flux in the z band"),
    ("sof_cm_flux_g", "Measured SOF composite model flux [ADU]"),
    ("sof_cm_flux_i", "Measured SOF composite model flux [ADU]"),
    ("sof_cm_flux_r", "Measured SOF composite model flux [ADU]"),
    ("sof_cm_flux_s2n_g", "SOF composite model flux signal to noise ratio"),
    ("sof_cm_flux_s2n_i", "SOF composite model flux signal to noise ratio"),
    ("sof_cm_flux_s2n_r", "SOF composite model flux signal to noise ratio"),
    ("sof_cm_flux_s2n_z", "SOF composite model flux signal to noise ratio"),
    ("sof_cm_flux_z", "Measured SOF composite model flux [ADU]"),
    ("sof_cm_fracdev", "SOF composite model fraction of de Vaucouleurs flux: cm = fracdev * devaucouleurs + (1-fracdev) * exponential"),
    ("sof_cm_fracdev_err", "Error in FRACDEV"),
    ("sof_cm_fracdev_noclip", "Value of FRACDEV if not clipped to [0,1] range"),
    ("sof_cm_g_1", "SOF based shape component 1 (reduced version of e1)"),
    ("sof_cm_g_2", "SOF based shape component 2 (reduced version of e2)"),
    ("sof_cm_g_cov_1_1", "SOF based shape covariance component 1-1"),
    ("sof_cm_g_cov_1_2", "SOF based shape covariance component 1-2"),
    ("sof_cm_g_cov_2_1", "SOF based shape covariance component 2-1"),
    ("sof_cm_g_cov_2_2", "SOF based shape covariance component 2-2"),
    ("sof_cm_logsb_g", "Logarithm of the SOF based surface brightness"),
    ("sof_cm_logsb_i", "Logarithm of the SOF based surface brightness"),
    ("sof_cm_logsb_r", "Logarithm of the SOF based surface brightness"),
    ("sof_cm_logsb_z", "Logarithm of the SOF based surface brightness"),
    ("sof_cm_mag_corrected_g", "SOF corrected magnitude = SOF_CM_MAG + DELTA_MAG_Y4 + DELTA_MAG_CHROM + A_SED_SFD98"),
    ("sof_cm_mag_corrected_i", "SOF corrected magnitude = SOF_CM_MAG + DELTA_MAG_Y4 + DELTA_MAG_CHROM + A_SED_SFD98"),
    ("sof_cm_mag_corrected_r", "SOF corrected magnitude = SOF_CM_MAG + DELTA_MAG_Y4 + DELTA_MAG_CHROM + A_SED_SFD98"),
    ("sof_cm_mag_corrected_z", "SOF corrected magnitude = SOF_CM_MAG + DELTA_MAG_Y4 + DELTA_MAG_CHROM + A_SED_SFD98"),
    ("sof_cm_mag_err_g", "Uncertainty in SOF magnitude"),
    ("sof_cm_mag_err_i", "Uncertainty in SOF magnitude"),
    ("sof_cm_mag_err_r", "Uncertainty in SOF magnitude"),
    ("sof_cm_mag_err_z", "Uncertainty in SOF magnitude"),
    ("sof_cm_mag_g", "Magnitude from SOF_CM_FLUX. MAG = 30-2.5*log10(FLUX)"),
    ("sof_cm_mag_i", "Magnitude from SOF_CM_FLUX. MAG = 30-2.5*log10(FLUX)"),
    ("sof_cm_mag_r", "Magnitude from SOF_CM_FLUX. MAG = 30-2.5*log10(FLUX)"),
    ("sof_cm_mag_z", "Magnitude from SOF_CM_FLUX. MAG = 30-2.5*log10(FLUX)"),
    ("sof_cm_t", "Size squared of the object: T=+ [arcsec**2]"),
    ("sof_cm_t_err", "Error in size squared [arcsec**2]"),
    ("sof_cm_tdbyte", "Ratio of sizes Tdev/Texp"),
    ("sof_flags", "Overall image processing flags. Can contain NULLs for objects with unfinished processing for SOF"),
    ("sof_psf_flux_err_g", "Uncertainty in measured SOF PSF flux [ADU]"),
    ("sof_psf_flux_err_i", "Uncertainty in measured SOF PSF flux [ADU]"),
    ("sof_psf_flux_err_r", "Uncertainty in measured SOF PSF flux [ADU]"),
    ("sof_psf_flux_err_z", "Uncertainty in measured SOF PSF flux [ADU]"),
    ("sof_psf_flux_g", "Measured SOF PSF flux [ADU]"),
    ("sof_psf_flux_i", "Measured SOF PSF flux [ADU]"),
    ("sof_psf_flux_r", "Measured SOF PSF flux [ADU]"),
    ("sof_psf_flux_s2n_g", "SOF PSF flux signal to noise ratio"),
    ("sof_psf_flux_s2n_i", "SOF PSF flux signal to noise ratio"),
    ("sof_psf_flux_s2n_r", "SOF PSF flux signal to noise ratio"),
    ("sof_psf_flux_s2n_z", "SOF PSF flux signal to noise ratio"),
    ("sof_psf_flux_z", "Measured SOF PSF flux [ADU]"),
    ("sof_psf_mag_err_g", "Uncertainty in SOF PSF magnitude"),
    ("sof_psf_mag_err_i", "Uncertainty in SOF PSF magnitude"),
    ("sof_psf_mag_err_r", "Uncertainty in SOF PSF magnitude"),
    ("sof_psf_mag_err_z", "Uncertainty in SOF PSF magnitude"),
    ("sof_psf_mag_g", "Magnitude from SOF_PSF_FLUX. MAG = 30-2.5*log10(FLUX)"),
    ("sof_psf_mag_i", "Magnitude from SOF_PSF_FLUX. MAG = 30-2.5*log10(FLUX)"),
    ("sof_psf_mag_r", "Magnitude from SOF_PSF_FLUX. MAG = 30-2.5*log10(FLUX)"),
    ("sof_psf_mag_z", "Magnitude from SOF_PSF_FLUX. MAG = 30-2.5*log10(FLUX)"),
    ("spread_model_g", "Morphology based classifier based on a linear discriminant between the pixel map of the object convolved with the PSF model and the pixel map convolved with a PSF+exponential model. Values closer to 0 correspond to stars, larger values correspond to galaxies"),
    ("spread_model_i", "Morphology based classifier based on a linear discriminant between the pixel map of the object convolved with the PSF model and the pixel map convolved with a PSF+exponential model. Values closer to 0 correspond to stars, larger values correspond to galaxies"),
    ("spread_model_r", "Morphology based classifier based on a linear discriminant between the pixel map of the object convolved with the PSF model and the pixel map convolved with a PSF+exponential model. Values closer to 0 correspond to stars, larger values correspond to galaxies"),
    ("spread_model_y", "Morphology based classifier based on a linear discriminant between the pixel map of the object convolved with the PSF model and the pixel map convolved with a PSF+exponential model. Values closer to 0 correspond to stars, larger values correspond to galaxies"),
    ("spread_model_z", "Morphology based classifier based on a linear discriminant between the pixel map of the object convolved with the PSF model and the pixel map convolved with a PSF+exponential model. Values closer to 0 correspond to stars, larger values correspond to galaxies"),
    ("spreaderr_model_g", "Uncertainty in SPREAD_MODEL."),
    ("spreaderr_model_i", "Uncertainty in SPREAD_MODEL."),
    ("spreaderr_model_r", "Uncertainty in SPREAD_MODEL."),
    ("spreaderr_model_y", "Uncertainty in SPREAD_MODEL."),
    ("spreaderr_model_z", "Uncertainty in SPREAD_MODEL."),
    ("theta_j2000", "Position angle of the ellipse fit to the object with the N/S/E/W axes in equatorial J2000 coordinates, from non-windowed measurement. THETA_J2000 = THETA_IMAGE-90(MOD 180) [degrees]"),
    ("tilename", "Identifier of each one of the tiles on which the survey is gridded for data processing"),
    ("wavg_flux_psf_g", "PSF flux using the weighted averaged values of single epoch objects (according to weight maps). Not valid if NEPOCHS = 0 [ADU]"),
    ("wavg_flux_psf_i", "PSF flux using the weighted averaged values of single epoch objects (according to weight maps). Not valid if NEPOCHS = 0 [ADU]"),
    ("wavg_flux_psf_r", "PSF flux using the weighted averaged values of single epoch objects (according to weight maps). Not valid if NEPOCHS = 0 [ADU]"),
    ("wavg_flux_psf_y", "PSF flux using the weighted averaged values of single epoch objects (according to weight maps). Not valid if NEPOCHS = 0 [ADU]"),
    ("wavg_flux_psf_z", "PSF flux using the weighted averaged values of single epoch objects (according to weight maps). Not valid if NEPOCHS = 0 [ADU]"),
    ("wavg_fluxerr_psf_g", "RMS error estimate of WAVG_FLUX_PSF [ADU]"),
    ("wavg_fluxerr_psf_i", "RMS error estimate of WAVG_FLUX_PSF [ADU]"),
    ("wavg_fluxerr_psf_r", "RMS error estimate of WAVG_FLUX_PSF [ADU]"),
    ("wavg_fluxerr_psf_y", "RMS error estimate of WAVG_FLUX_PSF [ADU]"),
    ("wavg_fluxerr_psf_z", "RMS error estimate of WAVG_FLUX_PSF [ADU]"),
    ("wavg_mag_psf_g", "Magnitude corresponding to MAG = 30-2.5*log10(WAVG_FLUX_PSF) [magnitudes]"),
    ("wavg_mag_psf_i", "Magnitude corresponding to MAG = 30-2.5*log10(WAVG_FLUX_PSF) [magnitudes]"),
    ("wavg_mag_psf_r", "Magnitude corresponding to MAG = 30-2.5*log10(WAVG_FLUX_PSF) [magnitudes]"),
    ("wavg_mag_psf_y", "Magnitude corresponding to MAG = 30-2.5*log10(WAVG_FLUX_PSF) [magnitudes]"),
    ("wavg_mag_psf_z", "Magnitude corresponding to MAG = 30-2.5*log10(WAVG_FLUX_PSF) [magnitudes]"),
    ("wavg_magerr_psf_g", "Uncertainty of WAVG_MAG_PSF, scaled from WAVG_FLUXERR_PSF [magnitudes]"),
    ("wavg_magerr_psf_i", "Uncertainty of WAVG_MAG_PSF, scaled from WAVG_FLUXERR_PSF [magnitudes]"),
    ("wavg_magerr_psf_r", "Uncertainty of WAVG_MAG_PSF, scaled from WAVG_FLUXERR_PSF [magnitudes]"),
    ("wavg_magerr_psf_y", "Uncertainty of WAVG_MAG_PSF, scaled from WAVG_FLUXERR_PSF [magnitudes]"),
    ("wavg_magerr_psf_z", "Uncertainty of WAVG_MAG_PSF, scaled from WAVG_FLUXERR_PSF [magnitudes]"),
    ("wavg_spread_model_g", "SPREAD MODEL using the weighted averaged values from single epoch detections"),
    ("wavg_spread_model_i", "SPREAD MODEL using the weighted averaged values from single epoch detections"),
    ("wavg_spread_model_r", "SPREAD MODEL using the weighted averaged values from single epoch detections"),
    ("wavg_spread_model_y", "SPREAD MODEL using the weighted averaged values from single epoch detections"),
    ("wavg_spread_model_z", "SPREAD MODEL using the weighted averaged values from single epoch detections"),
    ("wavg_spreaderr_model_g", "Uncertainty in WAVG_SPREAD_MODEL"),
    ("wavg_spreaderr_model_i", "Uncertainty in WAVG_SPREAD_MODEL"),
    ("wavg_spreaderr_model_r", "Uncertainty in WAVG_SPREAD_MODEL"),
    ("wavg_spreaderr_model_y", "Uncertainty in WAVG_SPREAD_MODEL"),
    ("wavg_spreaderr_model_z", "Uncertainty in WAVG_SPREAD_MODEL"),
    ("xwin_image", "X position of the barycenter of the object within the image using a Gaussian window with a FWHM corresponding to the radius of the aperture containing 50% of the flux [pixel]"),
    ("ywin_image", "Y position of the barycenter of the object within the image using a Gaussian window with a FWHM corresponding to the radius of the aperture containing 50% of the flux [pixel]"),
)

units = {
    "ADU": "adu",
    "magnitudes": "mag",
    "degrees": "deg",
}

# zeropoint of 30 is picomaggy, 22.5 nanomaggy
picomgy_to_nJy = (30*u.ABmag).to(u.nJy).value

for values in columns:
    if len(values) != 2:
        print(f"{values[0]} len={len(values)}")
        continue
    name, desc = values
    if name in tab_ap.colnames:
        if desc.endswith("]"):
            desc, unit = desc[:-1].rsplit(" [")
            unit = units.get(unit, unit)
        else:
            unit = ""
        column = tab_ap[name]
        if unit == "adu":
            tab_ap[name] *= picomgy_to_nJy
            # The above line makes a new column object for some reason
            column = tab_ap[name]
            unit = "nJy"

        column.unit = unit
        column.description = desc
    else:
        print(f"{name} column not found")

unit_ra = u.Unit(tab_ap["alphawin_j2000"].unit)
tab_ap["ra_gaia"] = tab_ap["alphawin_j2000"] + (0.1695*u.arcsec).to(unit_ra).value
tab_ap["ra_gaia"].description = "alphawin_j2000 +0.1695 arcsec (empirical Gaia correction)"
tab_ap["ra_gaia"].unit = unit_ra
unit_dec = u.Unit(tab_ap["deltawin_j2000"].unit)
tab_ap["dec_gaia"] = tab_ap["deltawin_j2000"] + (-0.039*u.arcsec).to(unit_dec).value
tab_ap["dec_gaia"].description = "deltawin_j2000 -0.039 arcsec (empirical Gaia correction)"
tab_ap["dec_gaia"].unit = unit_dec

tab_arrow = astropy_to_arrow(tab_ap)
row_group_size = compute_row_group_size(tab_arrow.schema)

pq.write_table(tab_arrow, f"{name_tab}.parq")
